Repository geoadmin/web-mapviewer, pull requests merged in 2022-11, with the labels that each got.

#268 BGDIINF_SB-2508: Added feedback on selection of drawing icon color.
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/DrawingStyleTextColorSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/scss/variables.scss
  src/setup-fontawesome.js
  src/utils/ButtonWithIcon.vue
  tests/e2e-cypress/integration/drawing/marker-text.cy.js
Labels: feature

#277 BGDIINF_SB-2476: Debounce the search bar
  src/modules/menu/components/search/SearchBar.vue
Labels: feature

#275 BGDIINF_SB-2508: Added feedback in drawing marker icon selection
  buildspec.yml
  src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/scss/webmapviewer-bootstrap-theme.scss
Labels: feature

#276 Harmonize share icons
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
Labels: feature

#280 BGDIINF_SB-2657: Added dynamic app versioning based on git tag
  package-lock.json
  package.json
  src/modules/map/components/footer/MapFooterAppVersion.vue
  vite.config.ts
Labels: feature

#279 Harmonize button spacer and remove duplicate delete button in drawing
  src/modules/i18n/components/LangSwitchToolbar.vue
  src/modules/infobox/components/FeatureProfile.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/menu/components/menu/MenuSettings.vue
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
  src/scss/variables.scss
  src/scss/webmapviewer-bootstrap-theme.scss
Labels: feature

#281 BGDIINF_SB-2657: Fixed versioning
  vite.config.ts
Labels: feature

#271 Bugfix 2211 measurment tool returns wrong results
  package-lock.json
  package.json
  src/api/features.api.js
  src/api/files.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingLineInteraction.vue
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/drawing/components/DrawingModifyInteraction.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/modifyInteraction.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/utils/MeasureManager.js
  src/utils/__tests__/geodesicManager.spec.js
  src/utils/coordinateUtils.js
  src/utils/geodesicManager.js
  tests/e2e-cypress/integration/drawing/export.cy.js
  tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/drawing/line-polygon.cy.js
  tests/e2e-cypress/integration/drawing/measureOverlays.cy.js
  tests/e2e-cypress/integration/drawing/profile.cy.js
  tests/e2e-cypress/integration/infobox.cy.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
  tests/e2e-cypress/support/commands.js
  tests/e2e-cypress/support/drawing.js
Labels: bug

#272 BGDIINF_SB-2502: add map saved text to drawing toolbox
  src/api/features.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingModifyInteraction.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/lib/export-utils.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: feature

#284 BGDIINF_SB-2608: Fixed missmatch between profile and geodesic line
  src/api/features.api.js
  src/modules/drawing/components/DrawingModifyInteraction.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/infobox/components/FeatureProfile.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/store/modules/features.store.js
  src/utils/coordinateUtils.js
  src/utils/geodesicManager.js
  tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
Labels: bug

#288 BGDIINF_SB-2671: Upload build artifacts to S3
  buildspec.yml
  package.json
  vite-plugins/generate-build-info.js
  vite.config.ts
Labels: feature

#290 BGDIINF_SB-2671: Put assets in version directory during build
  buildspec.yml
  package.json
  vite-plugins/generate-build-info.js
  vite.config.ts
Labels: feature

#291 Feature : Removing layout switch button
  src/modules/menu/components/menu/MenuSettings.vue
Labels: feature

#289 BGDIINF_SB-2614 : button harmonization
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/utils/DropdownButton.vue
  src/utils/PopoverButton.vue
  tests/e2e-cypress/integration/layers.cy.js
Labels: feature

#283 Feat 2235 rework click on mobile device
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/menu/MenuModule.vue
  src/store/modules/map.store.js
  src/store/plugins/click-on-map-management.plugin.js
  tests/e2e-cypress/integration/infobox.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/search/search-results.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#282 Improved look and feel of menu button
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/modules/menu/components/menu/MenuSettings.vue
  src/scss/webmapviewer-bootstrap-theme.scss
  src/utils/ButtonWithIcon.vue
  src/utils/ModalWithBackdrop.vue
  src/utils/PopoverButton.vue
Labels: feature

#292 Replace UNIX specific script in build pipeline
  vite-plugins/generate-build-info.js
Labels: feature

#285 BGDIINF_SB-2472 : better handling of empty profile
  package.json
  src/api/__tests__/profile.api.spec.js
  src/api/profile.api.js
  src/modules/drawing/lib/ProfileChart.js
  src/modules/drawing/lib/__tests__/profileChart.spec.js
  src/modules/drawing/lib/profileD3Utils.js
  src/modules/drawing/lib/profileUtils.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureCombo.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfileInformation.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureProfile.vue
  tests/e2e-cypress/fixtures/service-alti/profile.fixture.json
  tests/e2e-cypress/integration/drawing/export.cy.js
  tests/e2e-cypress/integration/drawing/profile.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#286 BGDIINF_SB-2660: Fixed index out of bounds exceptions when adding layers
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/utils/addLayerToMap-mixins.js
Labels: bug

#295 BGDIINF_SB-2660 : fix drawing layer not having a zIndex
  src/modules/drawing/DrawingModule.vue
Labels: bug

#299 BGDIINF_SB-2671: Fixed integration and production build
  .env.development
  .env.integration
  .env.production
  .gitignore
  buildspec.yml
  cypress.config.ts
  package.json
  scripts/deploy.js
  src/config.js
  tests/e2e-cypress/fixtures/service-kml/lonelyMarker.kml
  tests/e2e-cypress/fixtures/service-qrcode/position-popup.png
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/shareShortLink.cy.js
  vite.config.ts
Labels: feature

#300 BGDIINF_SB-2671: Fixed second artifact build
  buildspec.yml
Labels: bug

#301 New Release v0.2.0 - #minor
  .env.development
  .env.integration
  .env.production
  .gitignore
  buildspec.yml
  cypress.config.ts
  package.json
  scripts/deploy.js
  src/config.js
  tests/e2e-cypress/fixtures/service-kml/lonelyMarker.kml
  tests/e2e-cypress/fixtures/service-qrcode/position-popup.png
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/shareShortLink.cy.js
  vite.config.ts
Labels: new-release

#293 BGDIINF_SB-2671: Moved deployment scripts into infra-terraform-bgdi-builder
  .github/workflows/add-testlink-to-pr.yml
  buildspec.yml
  package.json
  scripts/deploy.js
  scripts/file-utils.js
  scripts/s3-utils.js
  tests/e2e-cypress/integration/deployScript.cy.js
Labels: feature

#304 Improved mouse position e2e tests
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: bug

#305 BGDIINF_SB-2671: Fixed CI int staging e2e tests
  package.json
Labels: bug

#308 BGDIINF_SB-2671: Fixed test:e2e:ci:int
  package.json
Labels: bug

#307 New Release v0.3.1 - #patch
  package.json
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: new-release

#309 BGDIINF_SB-2662: Use shortlink for position popup url
  package.json
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupCopyInput.vue
  src/modules/map/components/LocationPopupCopySlot.vue
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: feature

#297 BGDIINF_SB-2610: enhance legacy kml import
  src/api/__tests__/features.api.spec.js
  src/api/features.api.js
  src/api/icon.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/__tests__/mfgeoadmin3TestKml.kml
  src/utils/featureStyleUtils.js
  src/utils/legacyKmlUtils.js
  tests/e2e-cypress/fixtures/service-kml/lonelyMarker.kml
Labels: feature

#310 BGDIINF_SB-2662: Various bugfixes on position popup
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupCopyInput.vue
  src/modules/map/components/LocationPopupCopySlot.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
Labels: bug

#312 BGDIINF_SB-2661: Use shortlink to share kml drawings
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/SharePopup.vue
  tests/e2e-cypress/integration/drawing/share.cy.js
Labels: feature

#316 BGDIINF_SB-2708: Fixed map popover printing.
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/utils/print.js
Labels: bug

#313 BGDIINF_SB-2683: Fixed GeoJSON layers
  src/api/features.api.js
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
  src/modules/menu/components/search/SearchResultCategory.vue
  src/utils/__tests__/legacyKmlUtils.spec.js
Labels: bug

#315 BGDIINF_SB-2683: Improved html popover style
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
Labels: bug
