Repository geoadmin/web-mapviewer, pull requests merged in 2022-04, with the labels that each got.

#176 BGDIINF_SB-2228: Updated UI for link sharing
  src/main.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupCopyInput.vue
  src/modules/map/components/LocationPopupCopySlot.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/scss/variables.scss
  src/setup-fontawesome.js
  tests/e2e/specs/mouseposition.spec.js
Labels: feature

#192 BGDIINF_SB-2263: Added trigger to open/close menu
  src/App.vue
  src/config.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/menu/MenuModule.vue
  src/modules/store/modules/ui.store.js
  src/modules/store/plugins/screen-size-management.plugin.js
  src/utils/debounce.js
  tests/e2e/specs/drawing/delete.spec.js
  tests/e2e/specs/drawing/drawing-layer.spec.js
  tests/e2e/specs/drawing/export.spec.js
  tests/e2e/specs/drawing/kml.spec.js
  tests/e2e/specs/drawing/line-polygon.spec.js
  tests/e2e/specs/drawing/marker-text.spec.js
  tests/e2e/specs/header.spec.js
  tests/e2e/specs/layers.spec.js
  tests/e2e/specs/topics.spec.js
  tests/e2e/support/drawing.js
Labels: feature

#189 Refactor drawing
  package-lock.json
  package.json
  src/api/features.api.js
  src/api/icon.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/DrawingLineInteraction.vue
  src/modules/drawing/components/DrawingMarkerInteraction.vue
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/drawing/components/DrawingModifyInteraction.vue
  src/modules/drawing/components/DrawingSelectInteraction.vue
  src/modules/drawing/components/DrawingTextInteraction.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/components/ProfilePopup.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/components/drawingLine.mixin.js
  src/modules/drawing/components/styling/DrawingStylePopup.vue
  src/modules/drawing/lib/DrawingManager.js
  src/modules/drawing/lib/ProfileChart.js
  src/modules/drawing/lib/drawingStyleColor.js
  src/modules/drawing/lib/drawingStyleSizes.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/HighlightedFeatureList.vue
  src/modules/infobox/components/SelectedFeatureList.vue
  src/modules/infobox/components/TooltipBox.vue
  src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/DrawingStyleSizeSelector.vue
  src/modules/infobox/components/styling/DrawingStyleTextColorSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/infobox/components/styling/SelectedFeatureProfile.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/modules/store/index.js
  src/modules/store/modules/drawing.store.js
  src/modules/store/modules/feature.store.js
  src/modules/store/modules/features.store.js
  src/utils/ButtonWithIcon.vue
  src/utils/EventEmitter.class.js
  src/utils/PopoverButton.vue
  src/utils/featureStyleUtils.js
  tests/e2e/specs/infobox.spec.js
  tests/unit/drawingUtils.spec.js
Labels: feature

#194 Changed the event to prevent too many triggers
  src/modules/drawing/components/DrawingSelectInteraction.vue
Labels: new-release

#195 Fixed drawing tooltip and tolerances
  src/config.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingModifyInteraction.vue
  src/modules/drawing/components/DrawingSelectInteraction.vue
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/lib/drawingUtils.js
Labels: new-release

#196 Consolidated store on top-level
  README.md
  adr/2022_04_11_vuex_store_consolidation.md
  src/main.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/drawing/components/ProfilePopup.vue
  src/modules/i18n/components/LangSwitchToolbar.vue
  src/modules/i18n/store/index.js
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupCopyInput.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/store/index.js
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/menu/MenuSettings.vue
  src/modules/menu/store/index.js
  src/modules/store/README.md
  src/router/index.js
  src/store/README.md
  src/store/index.js
  src/store/modules/app.store.js
  src/store/modules/drawing.store.js
  src/store/modules/feature.store.js
  src/store/modules/geolocation.store.js
  src/store/modules/i18n.store.js
  src/store/modules/layers.store.js
  src/store/modules/map.store.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/store/modules/topics.store.js
  src/store/modules/ui.store.js
  src/store/plugins/app-readiness.plugin.js
  src/store/plugins/click-on-map-management.plugin.js
  src/store/plugins/drawing-layer-management.plugin.js
  src/store/plugins/geolocation-management.plugin.js
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/store/plugins/loading-bar-management.plugin.js
  src/store/plugins/menu-search-interaction.plugin.js
  src/store/plugins/redo-search-on-lang-change.plugin.js
  src/store/plugins/screen-size-management.plugin.js
  src/store/plugins/topic-change-management.plugin.js
  tests/unit/zoom.spec.js
Labels: feature

#198 Fixed some of the e2e tests after the rewrite
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/lib/ProfileChart.js
  src/modules/store/plugins/drawing-layer-management.plugin.js
  tests/e2e/specs/drawing/delete.spec.js
  tests/e2e/specs/drawing/drawing-layer.spec.js
  tests/e2e/specs/drawing/export.spec.js
  tests/e2e/specs/drawing/kml.spec.js
  tests/e2e/specs/drawing/line-polygon.spec.js
  tests/e2e/specs/drawing/marker-text.spec.js
  tests/e2e/specs/drawing/profile.spec.js
  tests/e2e/support/drawing.js
Labels: bug

#201 BGDIINF_SB-2358: Fixed drawing export e2e tests
  src/modules/drawing/lib/export-utils.js
  tests/e2e/plugins/index.js
  tests/e2e/specs/drawing/export.spec.js
  tests/e2e/support/drawing.js
Labels: bug

#202 BGDIINF_SB-2360: Updated width and added auto-pan
  src/modules/infobox/components/SelectedFeatureList.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/scss/variables.scss
  tests/e2e/specs/drawing/line-polygon.spec.js
Labels: bug

#204 BGDIINF_SB-2370: Use the correct address for test link
  .github/workflows/add-testlink-to-pr.yml
  CONTRIBUTING.md
  README.md
  scripts/deploy.js
Labels: skip-release-note
