Repository geoadmin/web-mapviewer, pull requests merged in 2022-12, with the labels that each got.

#314 BGDIINF_SB-2695: Fixed modal black drop
  src/modules/drawing/components/SharePopup.vue
  src/modules/menu/components/BlackBackdrop.vue
  src/utils/ModalWithBackdrop.vue
  tests/e2e-cypress/integration/drawing/share.cy.js
Labels: bug

#318 BGDIINF_SB-2683: Fixed padding in infobox and popover
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
Labels: bug

#317 Fixed elevation profile crash on windows resize
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
Labels: bug

#321 Fix_BGDIINF_SB-2682 no more doubling of wms layers on other side of globe
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
Labels: bug

#322 BGDIINF_SB-2678 Made the test banner dynamic based on hostname
  src/config.js
  src/modules/map/MapModule.vue
  src/modules/map/components/WarningRibbon.vue
  src/modules/map/components/footer/MapFooterAppVersion.vue
  src/modules/menu/components/header/HeaderSwissConfederationText.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/header/SwissFlag.vue
  src/scss/variables.scss
  src/store/modules/ui.store.js
  tests/e2e-cypress/integration/footer.cy.js
  tests/e2e-cypress/integration/ribbon.cy.js
Labels: feature

#327 New Release v0.4.0 - #minor
  package.json
  src/api/__tests__/features.api.spec.js
  src/api/features.api.js
  src/api/icon.api.js
  src/config.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/components/SharePopup.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/MapModule.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupCopyInput.vue
  src/modules/map/components/LocationPopupCopySlot.vue
  src/modules/map/components/WarningRibbon.vue
  src/modules/map/components/footer/MapFooterAppVersion.vue
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
  src/modules/menu/components/BlackBackdrop.vue
  src/modules/menu/components/header/HeaderSwissConfederationText.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/header/SwissFlag.vue
  src/modules/menu/components/search/SearchResultCategory.vue
  src/scss/variables.scss
  src/store/modules/ui.store.js
  src/utils/ModalWithBackdrop.vue
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/__tests__/mfgeoadmin3TestKml.kml
  src/utils/featureStyleUtils.js
  src/utils/legacyKmlUtils.js
  src/utils/print.js
  tests/e2e-cypress/fixtures/service-kml/lonelyMarker.kml
  tests/e2e-cypress/integration/drawing/share.cy.js
  tests/e2e-cypress/integration/footer.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/ribbon.cy.js
Labels: new-release

#325 BGDIINF_SB-2668: Fixed empty drawing being saved and displayed in menu
  src/modules/drawing/DrawingModule.vue
  tests/e2e-cypress/integration/drawing/kml.cy.js
Labels: bug

#330 BGDIINF_SB-2678: Banner bug
  src/config.js
  src/store/modules/ui.store.js
Labels: bug

#326 BGDIINF_SB-2729: Added multiple KML edit and simplify KML drawing logic
  src/api/files.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/SharePopup.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/store/index.js
  src/store/modules/drawing.store.js
  src/store/plugins/drawing-layer-management.plugin.js
  tests/e2e-cypress/fixtures/service-kml/create-file.fixture.json
  tests/e2e-cypress/fixtures/service-kml/update-file.fixture.json
  tests/e2e-cypress/integration/drawing/drawing-layer.cy.js
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/drawing/line-polygon.cy.js
  tests/e2e-cypress/integration/drawing/marker-text.cy.js
  tests/e2e-cypress/integration/drawing/share.cy.js
  tests/e2e-cypress/support/commands.js
  tests/e2e-cypress/support/drawing.js
Labels: feature

#329 Updating doc regarding app deployment
  README.md
Labels: bug

#331 BGDIINF_SB-2729: Fixed save KML drawing error handling - from post review of #326
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/lib/export-utils.js
Labels: bug
