Repository geoadmin/web-mapviewer, pull requests merged in 2023-03, with the labels that each got.

#383 BGDIINF_SB-2792 : fix layer ordering
  src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/store/modules/layers.store.js
  src/store/plugins/topic-change-management.plugin.js
  tests/e2e-cypress/integration/layers.cy.js
  tests/e2e-cypress/integration/topics.cy.js
Labels: bug

#377 feat_BGDIINF_SB-2788: removing pixelkarte grau background layer
  src/modules/map/components/footer/MapFooterBackgroundSelector.vue
  src/scss/variables-admin.scss
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/store/plugins/topic-change-management.plugin.js
Labels: feature

#373 BGDIINF_SB-2680 : remove ButtonWithIcon component
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/DrawingHeader.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/styling/DrawingStylePopoverButton.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/modules/menu/components/share/MenuShareEmbed.vue
  src/modules/menu/components/topics/MenuTopicTreeItem.vue
  src/setup-fontawesome.js
  src/utils/ButtonWithIcon.vue
  src/utils/ModalWithBackdrop.vue
  src/utils/PopoverButton.vue
Labels: feature

#389 BGDIINF_SB-2743 : aggregate TippyJS usage for third party disclaimer
  src/modules/map/components/footer/MapFooter.vue
  src/modules/map/components/footer/MapFooterAttribution.vue
  src/modules/map/components/footer/MapFooterAttributionItem.vue
  src/modules/map/components/footer/MapFooterAttributionList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/utils/ThirdPartDisclaimer.vue
Labels: bug

#368 try to us the same font size as in the current UI
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/search/SearchBar.vue
Labels: bug

#395 BGDIINF_SB-2816: drawing feature text boxes read only
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
Labels: bug, feature

#396 BGDIINF_SB-2829: Text in tooltips is now selectable
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
Labels: bug

#392 BGDIINF_SB-2785: Infobox does not hide menu anymore in phone mode
  src/modules/map/components/footer/MapFooter.vue
  src/scss/variables.scss
Labels: feature
