Repository geoadmin/web-mapviewer, pull requests merged in 2023-10, with the labels that each got.

#453 Added an npm target to check the code formatting
  package.json
  tests/e2e-cypress/fixtures/geojson-style.fixture.json
  tests/e2e-cypress/fixtures/geojson.fixture.json
Labels: feature

#452 BGDIINF_SB-2430: Improved sharing embed previzualization
  src/modules/menu/components/share/MenuShareEmbed.vue
  src/modules/menu/components/share/MenuShareInputCopyButton.vue
  src/modules/menu/components/share/MenuShareSection.vue
  src/setup-fontawesome.js
  tests/e2e-cypress/integration/shareShortLink.cy.js
Labels: feature

#446 BGDIINF_SB-2890 : add projection as props for all mapping components
  src/config.js
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/store/modules/position.store.js
Labels: feature

#448 BGDIINF_SB-2890 : add debug button to toggle projection
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/toolboxRight/ToggleProjectionButton.vue
  src/setup-fontawesome.js
Labels: feature

#458 BGDIINF_SB-2890: Fixed KML coordinates format during exports
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/lib/export-utils.js
Labels: feature, data-integration

#456 BGDIINF_SB-2430: Improved again share embed menu
  src/modules/menu/components/share/MenuShareEmbed.vue
Labels: feature

#459 BGDIINF_SB-2890: KML now stores only the geometries in standard KML element in WGS84
  src/api/__tests__/features.api.spec.js
  src/api/features.api.js
  src/api/icon.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/featureStyleUtils.js
  src/utils/legacyKmlUtils.js
  tests/e2e-cypress/fixtures/html-popup.fixture.html
Labels: feature

#460 BGDIINF_SB-2890: Fixed crash when editing a drawing component
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
Labels: bug, data-integration

#447 BGDIINF_SB-2890 : reproject map content when projection changes
  src/api/__tests__/features.api.spec.js
  src/api/features.api.js
  src/api/icon.api.js
  src/api/layers/AbstractLayer.class.js
  src/api/profile/profile.api.js
  src/api/what3words.api.js
  src/config.js
  src/main.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/drawingInteraction.mixin.js
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
  src/store/index.js
  src/store/modules/__tests__/zoom.store.spec.js
  src/store/modules/position.store.js
  src/store/plugins/reproject-everything-on-projection-change.plugin.js
  src/store/plugins/sync-camera-lonlatzoom.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/__tests__/zoomLevelUtils.spec.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/utils/coordinates/CoordinateSystemBounds.class.js
  src/utils/coordinates/__test__/CoordinateSystemBounds.class.spec.js
  src/utils/coordinates/coordinateFormat.js
  src/utils/coordinates/coordinateSystems.js
  src/utils/featureStyleUtils.js
  src/utils/legacyKmlUtils.js
  src/utils/setupProj4.js
  src/utils/zoomLevelUtils.js
  tests/e2e-cypress/fixtures/html-popup.fixture.html
  tests/e2e-cypress/integration/3d/navigation.cy.js
  tests/e2e-cypress/integration/drawing/marker-text.cy.js
  tests/e2e-cypress/integration/footer.cy.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
Labels: feature

#462 BGDIINF_SB-2890: Fixed drawing moving component
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/map/components/MapPopover.vue
Labels: bug, data-integration

#465 BGDIINF_SB-2890 : add projection EPSG number as URL param
  src/router/storeSync/storeSync.config.js
  src/store/modules/position.store.js
Labels: feature

#463 BGDIINF_SB-2890 : add center as new URL param (replaces lat lon)
  src/api/topics.api.js
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/PositionParamConfig.class.js
  src/router/storeSync/storeSync.config.js
  src/store/modules/__tests__/zoom.store.spec.js
  src/store/modules/position.store.js
  src/store/plugins/sync-camera-lonlatzoom.js
  src/utils/coordinates/coordinateFormat.js
  tests/e2e-cypress/integration/infobox.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#466 BGDIINF_SB-2890 : rework how Height and Search API handle projections
  src/api/height.api.js
  src/api/search.api.js
  src/modules/map/components/LocationPopup.vue
  src/store/modules/search.store.js
Labels: feature

#469 BGDIINF_SB-2890: Deactivate some tools in drawing mode
  src/modules/menu/MenuModule.vue
  src/modules/menu/scss/toolbox-buttons.scss
Labels: bug

#450 BGDIINF_SB-3070 : external layer import overlay
  src/external-layer-providers.json
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/ImportContent.vue
  src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/store/modules/ui.store.js
  src/utils/file.js
  src/utils/url.js
Labels: feature

#474 Fixed time slider toggling and button visibility
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/timeslider/TimeSlider.vue
  src/store/modules/layers.store.js
Labels: bug

#473 BGDIINF_SB-2890 : fix some e2e tests after LV95 work
  tests/e2e-cypress/integration/legacyParamImport.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: feature

#479 Add test link to PR to `develop-*` branches
  .github/workflows/add-testlink-to-pr.yml
Labels: feature

#481 BGDIINF_SB-2685: Fixed legacy KML protection
  src/modules/menu/components/menu/MenuTray.vue
  src/router/storeSync/LayerParamConfig.class.js
Labels: bug

#480 BGDIINF_SB-2890: Disable drawing menu when in 3D mode
  src/modules/menu/components/menu/MenuTray.vue
Labels: bug

#477 BGDIINF_SB-2890: Fixed elevation profile tracking in lv95
  src/api/features.api.js
  src/api/profile/profile.api.js
  src/modules/drawing/components/DrawingLineInteraction.vue
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/FeatureElevationProfilePlotCesiumBridge.vue
  src/modules/infobox/FeatureElevationProfilePlotOpenLayersBridge.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/styling/SelectedFeatureProfile.vue
  src/store/plugins/reproject-everything-on-projection-change.plugin.js
  src/utils/__tests__/geodesicManager.spec.js
  src/utils/geodesicManager.js
  tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
Labels: bug, WIP

#482 BGDIINF_SB-2890: Fixed 3d to 2d center of map
  src/modules/map/components/cesium/CesiumMap.vue
Labels: bug

#483 BGDIINF_SB-2890: Small bugfixes
  src/api/profile/ElevationProfile.class.js
  src/api/profile/profile.api.js
  src/modules/infobox/components/FeatureCombo.vue
  tests/e2e-cypress/fixtures/service-alti/profile.fixture.csv
Labels: bug

#486 BGDIINF_SB-3146 : Fix: 3D drawing crash on camera move, disable 3D toggle button when draw
  src/modules/map/components/cesium/CesiumPopover.vue
  src/modules/menu/components/toolboxRight/Toggle3dButton.vue
Labels: feature

#485 BGDIINF_SB-2890: Fixing geodesie tests
  cypress.config.ts
  src/store/modules/position.store.js
  tests/e2e-cypress/integration/drawing/geodesicDrawing.cy.js
  tests/e2e-cypress/support/commands.js
Labels: bug

#471 BGDIINF_SB-2890: better handling of zoom conversion
  src/api/profile/profile.api.js
  src/api/search.api.js
  src/api/what3words.api.js
  src/config.js
  src/main.js
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/PositionParamConfig.class.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/store/plugins/reproject-everything-on-projection-change.plugin.js
  src/store/plugins/sync-camera-lonlatzoom.js
  src/utils/__tests__/zoomLevelUtils.spec.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/utils/coordinates/CoordinateSystemBounds.class.js
  src/utils/coordinates/CustomCoordinateSystem.class.js
  src/utils/coordinates/LV03CoordinateSystem.class.js
  src/utils/coordinates/LV95CoordinateSystem.class.js
  src/utils/coordinates/StandardCoordinateSystem.class.js
  src/utils/coordinates/SwissCoordinateSystem.class.js
  src/utils/coordinates/WGS84CoordinateSystem.class.js
  src/utils/coordinates/WebMercatorCoordinateSystem.class.js
  src/utils/coordinates/__test__/CoordinateSystem.class.spec.js
  src/utils/coordinates/__test__/SwissCoordinateSystem.class.spec.js
  src/utils/coordinates/coordinateFormat.js
  src/utils/coordinates/coordinateSystems.js
  src/utils/zoomLevelUtils.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: bug

#487 Updated timeout in Cypress config
  cypress.config.ts
  tests/e2e-cypress/integration/infobox.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#488 BGDIINF_SB-2890 : fix some e2e tests
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/utils/setupProj4.js
  tests/e2e-cypress/integration/3d/navigation.cy.js
  tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/drawing/marker-text.cy.js
  tests/e2e-cypress/integration/drawing/share.cy.js
Labels: bug

#489 BGDIINF_SB-2890 : fix search tests
  src/api/search.api.js
  src/store/modules/search.store.js
  tests/e2e-cypress/fixtures/features.fixture.json
  tests/e2e-cypress/integration/search/search-results.cy.js
Labels: bug

#490 BGDIINF_SB-2890 : fix 3d/layers e2e test
  src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/addPrimitiveFromOLLayer.mixins.js
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/store/index.js
  src/store/plugins/2d-to-3d-management.plugin.js
  src/utils/geoJsonUtils.js
  tests/e2e-cypress/fixtures/features.fixture.json
Labels: bug

#476 BGDIINF_SB-3084 : GUI for import results
  src/api/layers/ExternalGroupOfLayers.class.js
  src/api/layers/ExternalLayer.class.js
  src/api/layers/ExternalWMSLayer.class.js
  src/api/layers/ExternalWMTSLayer.class.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/components/ImportContentResultItem.vue
  src/modules/infobox/components/ImportContentResultList.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/setup-fontawesome.js
  src/store/modules/__tests__/layers.store.spec.js
  src/store/modules/layers.store.js
  src/utils/file.js
  tests/e2e-cypress/integration/infobox.cy.js
Labels: feature

#492 BGDIINF_SB-3071: Added CLI tool to check the external providers
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/check-external-layers-providers.js
  src/external-layer-providers.json
  src/modules/drawing/components/SharePopup.vue
  src/modules/infobox/components/ImportContent.vue
  src/modules/map/components/LocationPopup.vue
  src/router/index.js
  src/utils/__tests__/urlQuery.spec.js
  src/utils/external-provider.js
  src/utils/file.js
  src/utils/url-router.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
Labels: feature

#494 BGDIINF_SB-3071, BGDIINF_SB-2890: Update import tool to work with lv95 default projection
  src/modules/infobox/components/ImportContent.vue
  src/utils/file.js
Labels: feature

#495 BGDIINF_SB-2890: Made the geolocation working with any projection
  src/store/plugins/geolocation-management.plugin.js
Labels: feature

#496 BGDIINF_SB-2890: Fixed what3words in popup location
  src/api/what3words.api.js
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
Labels: feature

#497 BGDIINF_SB-2890: Get rid of some default projection and fixed a bug in the import tool
  src/api/layers/AbstractLayer.class.js
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeature.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/store/plugins/click-on-map-management.plugin.js
Labels: feature
