Repository geoadmin/web-mapviewer, pull requests merged in 2023-02, with the labels that each got.

#362 BGDIINF_SB-2747: Add KML disclaimer icon and external disclaimer warning
  src/api/layers/KMLLayer.class.js
  src/modules/map/components/footer/MapFooterAttribution.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/store/modules/layers.store.js
  src/utils/ButtonWithIcon.vue
  src/utils/ModalWithBackdrop.vue
  src/utils/__tests__/legacyLayerParamUtils.spec.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
Labels: feature

#363 BGDIINF_SB-2764 : add feedback form
  setup-fontawesome.js
  src/api/feedback.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/menu/FeedbackButton.vue
  src/modules/menu/components/menu/FeedbackToolbar.vue
  src/modules/menu/components/menu/MenuSettings.vue
  src/modules/menu/components/menu/feedback/FeedbackButton.vue
  src/modules/menu/components/menu/feedback/FeedbackRating.vue
  src/modules/menu/components/menu/feedback/FeedbackToolbar.vue
  src/setup-fontawesome.js
  src/utils/ModalWithBackdrop.vue
  tests/e2e-cypress/integration/feedback.cy.js
Labels: feature

#366 fixing trivial link error in doc
  README.md
Labels: bug

#367 BGDIINF_SB-2772 : add styling back to delete last point button
  src/modules/drawing/components/DrawingToolbox.vue
Labels: bug

#375 BGDIINF_SB-2784 : fix Swiss flag position on smaller devices
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/header/SwissFlag.vue
  src/scss/variables.scss
Labels: bug

#376 BGDIINF_SB-2783 : add back light base map copyrights
  src/modules/map/components/footer/MapFooterAttribution.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/store/modules/position.store.js
Labels: bug

#370 BGDIINF_SB-2769 : add email input in feedback form
  src/api/feedback.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/menu/feedback/FeedbackButton.vue
  src/modules/menu/components/menu/feedback/FeedbackRating.vue
  tests/e2e-cypress/integration/feedback.cy.js
Labels: feature

#369 Updating translations for search bar
  src/modules/menu/components/header/HeaderWithSearch.vue
Labels: feature

#378 BGDIINF_SB-2790: Test banner now covers screen under the header
  src/modules/map/components/WarningRibbon.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
Labels: bug

#379 BGDIINF_SB-2793: leave menu open when searching
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/store/plugins/menu-search-interaction.plugin.js
Labels: feature

#380 New Release v1.1.0 - #minor
  README.md
  src/api/feedback.api.js
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/WarningRibbon.vue
  src/modules/map/components/footer/MapFooterAttribution.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/header/SwissFlag.vue
  src/modules/menu/components/menu/feedback/FeedbackButton.vue
  src/modules/menu/components/menu/feedback/FeedbackRating.vue
  src/scss/variables.scss
  src/store/modules/position.store.js
  src/store/plugins/menu-search-interaction.plugin.js
  tests/e2e-cypress/integration/feedback.cy.js
Labels: new-release

#381 Updated CI build status badge
  README.md
Labels: skip-release-note

#385 Updating the translation JSON generation script
  scripts/generate-i18n-files.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: feature
