Repository geoadmin/web-mapviewer, pull requests merged in 2023-11, with the labels that each got.

#502 Fix result selection bug in import tool
  src/modules/infobox/components/ImportContentResultList.vue
Labels: bug

#500 BGDIINF_SB-3071: Fixed bug in import tool for extent projection
  src/utils/file.js
Labels: bug

#505 BGDIINF_SB-2890: Removed lightbasemap under pixelkarte in webmercartor
  src/modules/map/components/footer/MapFooterAttributionList.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
Labels: feature

#503 BGDIINF_SB-3071: Moved the external-layer-providers.json in its module
  README.md
  scripts/check-external-layers-providers.js
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/utils/external-layer-providers.json
  src/modules/infobox/utils/external-provider.js
  tsconfig.json
Labels: feature

#506 BGDIINF_SB-2890: Fixed goelocation e2e tests
  tests/e2e-cypress/integration/geolocation.cy.js
Labels: bug

#507 BGDIINF_SB-2890 : move projection toggle into a debug toolbar
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/debug/DebugToolbar.vue
  src/modules/menu/components/debug/ToggleProjectionButton.vue
Labels: feature

#504 BGDIINF_SB-3071: Removed non working external layer provider
  scripts/check-external-layers-providers.js
  src/modules/infobox/utils/external-layer-providers.json
Labels: feature

#498 BGDIINF_SB-2890 : fix coordinate search
  src/api/what3words.api.js
  src/main.js
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/utils/coordinates/__test__/CoordinateSystem.class.spec.js
  src/utils/coordinates/__test__/coordinateExtractors.spec.js
  src/utils/coordinates/__test__/coordinateUtils.spec.js
  src/utils/coordinates/coordinateExtractors.js
  src/utils/coordinates/coordinateSystems.js
  src/utils/coordinates/coordinateUtils.js
  tests/e2e-cypress/integration/3d/navigation.cy.js
  tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/search/coordinates-search.cy.js
  tests/e2e-cypress/integration/search/search-results.cy.js
Labels: feature

#508 Update develop-lv95
  README.md
  scripts/check-external-layers-providers.js
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/components/ImportContentResultList.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/infobox/utils/external-layer-providers.json
  src/modules/infobox/utils/external-provider.js
  tsconfig.json
Labels: new-release

#510 BGDIINF_SB-2890: Fixed mouse position tests
  tests/e2e-cypress/integration/mouseposition.cy.js
Labels: bug

#509 BGDIINF_SB-2890: Fixed legacy parameters coordinates
  src/router/legacyPermalinkManagement.routerPlugin.js
  tests/e2e-cypress/integration/geolocation.cy.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
Labels: bug

#511 BGDIINF_SB-2890: Moved the debug tool bar to avoid overlapping infobox on mobile
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/debug/DebugToolbar.vue
  src/scss/webmapviewer-bootstrap-theme.scss
Labels: bug

#512 BGDIINF_SB-2890 : fix 3d tests
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/storeSync.config.js
  src/store/index.js
  src/store/modules/position.store.js
  src/store/plugins/reproject-everything-on-projection-change.plugin.js
  src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
  tests/e2e-cypress/integration/3d/layers.cy.js
  tests/e2e-cypress/support/commands.js
Labels: bug

#513 BGDIINF_SB-2890: fix infobox test
  src/api/features.api.js
  src/modules/menu/MenuModule.vue
  src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
  src/utils/coordinates/coordinateUtils.js
  tests/e2e-cypress/integration/infobox.cy.js
Labels: bug

#514 BGDIINF_SB-3162, BGDIINF_SB-3163: Fixed background in lv95
  src/modules/map/components/footer/MapFooterBackgroundSelector.vue
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/store/plugins/topic-change-management.plugin.js
Labels: feature

#491 BGDIINF_SB-3154 : make crosshair URL param dynamic
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/router/index.js
  src/router/storeSync/CrossHairParamConfig.class.js
  src/router/storeSync/storeSync.config.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/position.store.js
  tests/e2e-cypress/integration/crosshair.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#515 BGDIINF_SB-3168: Fix external layer parsing error (no `layer.name`)
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/components/ImportContentResultList.vue
  src/modules/infobox/utils/external-provider-parsers.js
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  src/modules/menu/components/menu/MenuTray.vue
  tests/e2e-cypress/fixtures/import-tool/wms-geo-admin-get-capabilities.xml
  tests/e2e-cypress/integration/importTool.cy.js
Labels: bug

#519 Fixed search bar category background
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/components/ImportContentResultItem.vue
  src/modules/menu/components/search/SearchBar.vue
  src/modules/menu/components/search/SearchResultCategory.vue
  src/modules/menu/components/search/SearchResultList.vue
  src/modules/menu/components/search/SearchResultListEntry.vue
  src/scss/webmapviewer-bootstrap-theme.scss
Labels: bug

#518 BGDIINF_SB-3170: Fixed group of external layers attributions
  src/api/layers/ExternalGroupOfLayers.class.js
  src/modules/infobox/utils/external-provider-parsers.js
  src/utils/ModalWithBackdrop.vue
  tests/e2e-cypress/integration/importTool.cy.js
  tests/e2e-cypress/support/commands.js
  tests/e2e-cypress/support/utils.js
Labels: bug

#520 BGDIINF_SB-3174 : add labels, buildings and vegetation to 3D
  .env.development
  .env.integration
  .env.production
  README.md
  adr/2023_11_08_vue_composition_api.md
  src/api/layers/GeoAdmin3DLayer.class.js
  src/api/layers/GeoAdminVectorLayer.class.js
  src/api/layers/layers.api.js
  src/config.js
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/map/MapModule.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumVectorLayer.vue
  src/modules/map/components/cesium/utils/primitiveLayerUtils.js
  src/modules/map/components/openlayers/OpenLayersVectorLayer.vue
  src/modules/menu/components/debug/DebugToolbar.vue
  src/modules/menu/components/debug/Toggle3DLayerButton.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/toolboxRight/Toggle3dButton.vue
  src/router/storeSync/CameraParamConfig.class.js
  src/router/storeSync/__tests__/CameraParamConfig.class.spec.js
  src/router/storeSync/storeSync.config.js
  src/setup-fontawesome.js
  src/store/index.js
  src/store/modules/cesium.store.js
  src/store/modules/map.store.js
  src/store/modules/ui.store.js
  src/store/plugins/2d-to-3d-management.plugin.js
  src/views/MapView.vue
  tests/e2e-cypress/fixtures/3d/tile.terrain
  tests/e2e-cypress/fixtures/3d/tile.vctr
  tests/e2e-cypress/fixtures/3d/tileset.json
  tests/e2e-cypress/integration/3d/click.cy.js
  tests/e2e-cypress/integration/3d/layers.cy.js
  tests/e2e-cypress/integration/3d/navigation.cy.js
  tests/e2e-cypress/integration/3d/transitionTo3d.cy.js
  tests/e2e-cypress/integration/infobox.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#524 BGDIINF_SB-3187: Reduce the number of tests for the search bar
  tests/e2e-cypress/integration/search/coordinates-search.cy.js
Labels: feature

#439 BGDIINF_SB-3059 : add location popup for 3D
  src/modules/map/MapModule.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumPopover.vue
Labels: feature

#523 BGDIINF_SB-3185 : rework of the BG selector
  src/api/layers/GeoAdmin3DLayer.class.js
  src/api/layers/GeoAdminAggregateLayer.class.js
  src/api/layers/GeoAdminGeoJsonLayer.class.js
  src/api/layers/GeoAdminLayer.class.js
  src/api/layers/GeoAdminWMSLayer.class.js
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/api/layers/layers.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/assets/ch.swisstopo.leichte-basiskarte_world-vt.png
  src/modules/map/assets/ch.swisstopo.pixelkarte-farbe.png
  src/modules/map/assets/ch.swisstopo.pixelkarte-grau.png
  src/modules/map/assets/ch.swisstopo.swissimage.png
  src/modules/map/assets/ch.swisstopo.swissimage_3d.png
  src/modules/map/assets/ch.swisstopo.swisstlm3d-karte-farbe_3d.png
  src/modules/map/assets/ch.swisstopo.swisstlm3d-karte-grau_3d.png
  src/modules/map/assets/void.png
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/utils/primitiveLayerUtils.js
  src/modules/map/components/footer/MapFooter.vue
  src/modules/map/components/footer/MapFooterBackgroundSelector.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelector.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelectorWheelRounded.vue
  src/modules/map/components/footer/backgroundSelector/bg-selector.scss
  src/modules/map/components/footer/backgroundSelector/useBackgroundSelector.js
  src/modules/map/components/footer/backgroundSelector/useBackgroundSelectorProps.js
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/menu/assets/backgrounds.jpg
  src/modules/menu/assets/backgrounds_mobile.png
  src/scss/tippy-theme.scss
  src/store/modules/__tests__/layers.store.spec.js
  src/store/modules/cesium.store.js
  src/store/modules/layers.store.js
  src/store/plugins/2d-to-3d-management.plugin.js
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/utils/__tests__/legacyLayerParamUtils.spec.js
  tests/e2e-cypress/integration/footer.cy.js
Labels: feature

#521 BGDIINF_SB-3161 : constrains OL to only show map in LV95 extent
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/utils/militaryGridProjection.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/support/commands.js
Labels: feature

#530 Remove lib ogc-parser
  package-lock.json
  package.json
  scripts/check-external-layers-providers.js
Labels: feature

#531 Remove unused npm targets
  README.md
  package.json
Labels: feature

#525 BGDIINF_SB-3187: Improved layers.api cypress tests
  tests/e2e-cypress/fixtures/layers.fixture.json
  tests/e2e-cypress/integration/layers.cy.js
Labels: feature

#533 BGDIINF_SB-3193 : topics are now group of layers
  src/api/layers/GeoAdminGroupOfLayers.class.js
  src/api/topics.api.js
  src/modules/menu/components/topics/LayerCatalogue.vue
  src/modules/menu/components/topics/LayerCatalogueItem.vue
  src/modules/menu/components/topics/MenuTopicSection.vue
  src/modules/menu/components/topics/MenuTopicTreeItem.vue
  src/store/modules/topics.store.js
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/store/plugins/topic-change-management.plugin.js
  tests/e2e-cypress/integration/topics.cy.js
Labels: feature

#528 BGDIINF_SB-3172 : Add local file import UI
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/components/ImportContentResultList.vue
  tests/e2e-cypress/integration/importTool.cy.js
Labels: feature

#534 Updated docu about composition API
  .eslintrc.js
  CONTRIBUTING.md
  LICENSE.md
  README.md
  ROADMAP.md
  adr/2020_04_06_javascript_framework_choice.md
  adr/2020_05_28_test_framework.md
  adr/2021_03_16_url_param_structure.md
  adr/2021_04_14_drawing_library.md
  adr/2022_05_09_mobile_click_behavior.md
  adr/2023_11_08_vue_composition_api.md
  package-lock.json
  package.json
  src/modules/infobox/README.md
Labels: feature

#535 BGDIINF_SB-3197 : fix issue with serverLayerId being not used correctly
  src/api/layers/GeoAdminAggregateLayer.class.js
  src/api/layers/GeoAdminWMSLayer.class.js
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
Labels: bug

#539 BGDIINF_SB-3199: Re-added lint rules and fixed linting issues
  .eslintrc.js
  src/api/features.api.js
  src/api/layers/AbstractLayer.class.js
  src/api/layers/KMLLayer.class.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/modifyInteraction.js
  src/modules/drawing/lib/style.js
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/QueryToStoreOnlyParamConfig.class.js
  src/router/storeSync/__tests__/CameraParamConfig.class.spec.js
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/store/modules/layers.store.js
  src/store/modules/position.store.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/utils/coordinates/CustomCoordinateSystem.class.js
  src/utils/coordinates/SwissCoordinateSystem.class.js
  src/utils/coordinates/__test__/SwissCoordinateSystem.class.spec.js
  src/utils/coordinates/coordinateExtractors.js
  src/utils/geodesicManager.js
  src/utils/legacyKmlUtils.js
  tests/e2e-cypress/integration/drawing/kml.cy.js
  tests/e2e-cypress/integration/drawing/marker-text.cy.js
  tests/e2e-cypress/integration/drawing/profile.cy.js
  tests/e2e-cypress/integration/drawing/share.cy.js
  tests/e2e-cypress/integration/footer.cy.js
  tests/e2e-cypress/integration/header.cy.js
  tests/e2e-cypress/integration/importTool.cy.js
  tests/e2e-cypress/integration/layers.cy.js
  tests/e2e-cypress/integration/menuTray.cy.js
  tests/e2e-cypress/integration/mouseposition.cy.js
  tests/e2e-cypress/integration/topics.cy.js
  tests/e2e-cypress/support/commands.js
  tests/e2e-cypress/support/drawing.js
  tests/e2e-cypress/support/index.js
Labels: bug

#536 BGDIINF_SB-3180: External Layer refresh attributes on reload
  src/api/layers/AbstractLayer.class.js
  src/api/layers/ExternalGroupOfLayers.class.js
  src/api/layers/ExternalLayer.class.js
  src/api/layers/ExternalWMSLayer.class.js
  src/api/layers/ExternalWMTSLayer.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/layers/WMTSCapabilitiesParser.class.js
  src/api/layers/layers-external.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/utils/external-provider-parsers.js
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/__tests__/LayerParamConfig.class.spec.js
  src/store/index.js
  src/store/modules/__tests__/layers.store.spec.js
  src/store/modules/layers.store.js
  src/store/plugins/external-layers.plugin.js
  src/utils/__tests__/legacyLayerParamUtils.spec.js
  src/utils/legacyLayerParamUtils.js
  tests/e2e-cypress/integration/legacyParamImport.cy.js
Labels: feature

#537 BGDIINF_SB-3180: Updated URL param ADR for the External Layers
  adr/2021_03_16_url_param_structure.md
Labels: feature

#543 Improve mobile navigation in 3D
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/cesium/CesiumMap.vue
Labels: feature

#538 BGDIINF_SB-3180: Use new Capabilities Parser for import tool
  scripts/check-external-layers-providers.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/layers/layers-external.api.js
  src/config.js
  src/modules/infobox/components/ImportContent.vue
  src/modules/infobox/utils/external-layer-providers.json
  src/modules/infobox/utils/external-provider-parsers.js
  src/modules/infobox/utils/external-provider.js
  src/store/modules/layers.store.js
  src/store/plugins/external-layers.plugin.js
Labels: feature

#546 Temporary remove the advanced tool menu on productive environment
  src/config.js
  src/modules/menu/components/menu/MenuTray.vue
Labels: feature

#549 BGDIINF_SB-3180: Added unit tests for external WMTS and WMS parsing
  src/api/layers/__tests__/WMSCapabitliesParser.class.spec.js
  src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
  src/api/layers/__tests__/wms-geoadmin-sample.xml
  src/api/layers/__tests__/wmts-ogc-sample.xml
Labels: feature
