Repository geoadmin/web-mapviewer, pull requests merged in 2024-05, with the labels that each got.

#813 PB-475 : Activate a couple post-processing shader in Cesium
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumVectorLayer.vue
  src/modules/map/components/cesium/utils/primitiveLayerUtils.js
Labels: feature

#809 PB-360: measurement label
  package-lock.json
  package.json
  src/api/print.api.js
  src/utils/__tests__/geodesicManager.spec.js
  src/utils/geodesicManager.js
Labels: bug

#802 PB-443: Set year on timeslider close
  src/modules/map/components/toolbox/TimeSlider.vue
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: feature

#817 PB-474: Add missing sublayer to fix missing aggregate layer on the map.
  src/api/layers/layers.api.js
Labels: bug

#816 PB-448: Make sure print area layer always on top.
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
Labels: bug

#810 Bugfix PB-128: implement client side zoom
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/api/layers/layers.api.js
  src/config.js
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/utils/coordinates/SwissCoordinateSystem.class.js
  src/utils/layerUtils.js
Labels: bug

#806 PB-414: marker overlapping title
  src/api/features/EditableFeature.class.js
  src/api/icon.api.js
  src/modules/drawing/components/DrawingMarkerInteraction.vue
  src/modules/drawing/components/DrawingSelectInteraction.vue
  src/modules/drawing/components/useDrawingModeInteraction.composable.js
  src/modules/drawing/useKmlDataManagement.composable.js
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/store/modules/features.store.js
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/__tests__/webmapviewerOffsetTestKml.kml
  src/utils/featureStyleUtils.js
  src/utils/kmlUtils.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#824 PB-437: Fix print scale
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/store/modules/print.store.js
  src/store/modules/ui.store.js
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#826 PB-319: Bugfix on time slider click not keeping changes when closing the time slider.
  src/modules/map/components/toolbox/TimeSlider.vue
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: bug

#827 PB-481: bugfix apply transparency instead of opacity
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  tests/cypress/tests-e2e/layers.cy.js
Labels: bug

#829 PB-425: Implement external WMS external layer in 3D
  src/api/layers/GeoAdmin3DLayer.class.js
  src/api/layers/GeoAdminAggregateLayer.class.js
  src/api/layers/GeoAdminGeoJsonLayer.class.js
  src/api/layers/GeoAdminGroupOfLayers.class.js
  src/api/layers/GeoAdminLayer.class.js
  src/api/layers/GeoAdminVectorLayer.class.js
  src/api/layers/GeoAdminWMSLayer.class.js
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/api/layers/layers.api.js
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/store/modules/__tests__/layers.store.spec.js
  src/store/plugins/load-layersconfig-on-lang-change.js
  src/utils/__tests__/legacyLayerParamUtils.spec.js
  src/utils/layerUtils.js
Labels: bug

#830 PB-493: Fixed Time slider input cutoff on 3d Maps
  src/modules/map/components/toolbox/TimeSlider.vue
  src/scss/main.scss
Labels: bug

#831 PB-498: Fixed time selector css on mobile
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
Labels: bug

#820 PB-368 : add "load more features" button in feature list
  src/api/features/features.api.js
  src/config.js
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/FeatureListCategory.vue
  src/modules/infobox/components/FeatureListCategoryItem.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/features.store.js
  src/store/plugins/click-on-map-management.plugin.js
  src/utils/__tests__/numberUtils.spec.js
  src/utils/components/ZoomToExtentButton.vue
  src/utils/numberUtils.js
  tests/cypress/fixtures/features.fixture.json
  tests/cypress/fixtures/features/featureDetail.fixture.json
  tests/cypress/fixtures/features/features.fixture.json
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/featureSelection.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: feature

#832 PB-468 Fixed Time-Slider sliding under the menu on smaller screens
  src/modules/map/components/toolbox/TimeSliderButton.vue
Labels: bug

#838 PB-502: fix topic images absence
  src/modules/menu/scss/topics-image.scss
Labels: bug

#840 PB-368 : fix e2e test feature coordinate randomizer
  tests/cypress/support/commands.js
Labels: bug

#833 PB-468 Fix arrow shift of time slider on the edges
  src/modules/map/components/toolbox/TimeSlider.vue
Labels: bug

#842 PB-507: Fix logging in production build
  src/utils/logging.js
Labels: bug

#837 PB-503: Several UI in menu improvements, especially on mobile
  src/modules/i18n/components/LangButton.vue
  src/modules/i18n/components/LangSwitchToolbar.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/LocationPopupPosition.vue
  src/modules/map/components/LocationPopupShare.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/settings/HelpLink.vue
  src/modules/menu/components/settings/MenuLangSelector.vue
  src/modules/menu/components/settings/MoreInfo.vue
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/modules/menu/components/settings/feedback/FeedbackButton.vue
  src/modules/menu/components/share/MenuShareSection.vue
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
  src/scss/variables.module.scss
  src/utils/components/CoordinateCopySlot.vue
Labels: bug

#844 PB-449: Removed the modal for report a problem and give feedback
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/modules/menu/components/settings/feedback/FeedbackButton.vue
  src/utils/components/SimpleWindow.vue
  src/utils/composables/useFieldValidation.js
  tests/cypress/tests-e2e/feedback.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: bug

#836 PB-486: Fix print area when map is rotated
  src/modules/map/components/openlayers/utils/printConstants.js
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/modules/map/components/toolbox/Toggle3dButton.vue
Labels: bug

#835 PB-491: 3D menu only when active
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/3d/MenuThreeD.vue
  src/modules/menu/components/LayerCatalogueItem.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/common/MenuItemCheckBox.vue
  src/modules/menu/components/menu/MenuSection.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/share/MenuShareSection.vue
  src/modules/menu/components/topics/MenuTopicSection.vue
  src/store/modules/cesium.store.js
  src/utils/components/ErrorButton.vue
  src/utils/composables/useTippyTooltip.js
Labels: feature

#828 PB-496: External WMTS layer in 3d
  src/api/layers/AbstractLayer.class.js
  src/api/layers/ExternalLayer.class.js
  src/api/layers/ExternalWMTSLayer.class.js
  src/api/layers/GeoAdminLayer.class.js
  src/api/layers/LayerTimeConfig.class.js
  src/api/layers/LayerTimeConfigEntry.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/layers/WMTSCapabilitiesParser.class.js
  src/api/layers/__tests__/WMTSCapabitliesParser.class.spec.js
  src/api/layers/__tests__/wmts-ogc-sample.xml
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
  src/router/storeSync/LayerParamConfig.class.js
  src/store/plugins/external-layers.plugin.js
  src/utils/__tests__/numberUtils.spec.js
  src/utils/layerUtils.js
  src/utils/numberUtils.js
  tests/cypress/fixtures/import-tool/wmts-geo-admin-get-capabilities.xml
  tests/cypress/tests-e2e/importToolMaps.cy.js
Labels: bug

#848 PB-373: Fix missing label on GeoJSON layer
  src/api/print.api.js
Labels: bug

#843 PB-489: Fix text offset
  cypress.config.mjs
  package-lock.json
  package.json
  src/api/print.api.js
  src/utils/featureStyleUtils.js
  tests/cypress/fixtures/print/label.kml
  tests/cypress/fixtures/print/old-geoadmin-label.kml
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#825 PB-447: legacy parser not switching to map view
  package-lock.json
  package.json
  src/router/appLoadingManagement.routerPlugin.js
  src/router/index.js
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/app.store.js
Labels: bug

#849 PB-518: Fix timeslider flickering and WMS time enabled layer update
  package-lock.json
  package.json
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/utils/layerUtils.js
Labels: bug

#823 PB-442: change timeslider css for partial data
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/map/components/toolbox/TimeSlider.vue
  tests/cypress/tests-e2e/shareShortLink.cy.js
Labels: feature

#850 PB-451, PB-518: Fix WMS time enabled layer update
  src/api/layers/LayerTimeConfigEntry.class.js
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/utils/layerUtils.js
Labels: bug

#851 PB-496: Added External WMS time config support
  src/api/features/features.api.js
  src/api/layers/ExternalWMSLayer.class.js
  src/api/layers/ExternalWMTSLayer.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
Labels: bug

#854 PB-530: Added print date to the print API spec
  src/api/print.api.js
  src/modules/i18n/index.js
  src/store/modules/i18n.store.js
Labels: bug

#852 PB-531: Improve report a problem error management for big files
  src/api/feedback.api.js
  src/modules/drawing/components/DrawingHeader.vue
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/utils/__tests__/utils.spec.js
  src/utils/components/FileInput.vue
  src/utils/numberUtils.js
  src/utils/utils.js
Labels: bug

#858 PB-496: Fix external layer error and time slider issue
  src/api/layers/ExternalLayer.class.js
  src/store/modules/layers.store.js
Labels: bug

#859 New Release v1.19.0 - #minor
  src/api/features/features.api.js
  src/api/feedback.api.js
  src/api/layers/ExternalLayer.class.js
  src/api/layers/ExternalWMSLayer.class.js
  src/api/layers/ExternalWMTSLayer.class.js
  src/api/layers/LayerTimeConfigEntry.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/print.api.js
  src/modules/drawing/components/DrawingHeader.vue
  src/modules/i18n/index.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/store/modules/features.store.js
  src/store/modules/i18n.store.js
  src/store/modules/layers.store.js
  src/utils/__tests__/utils.spec.js
  src/utils/components/FileInput.vue
  src/utils/layerUtils.js
  src/utils/numberUtils.js
  src/utils/utils.js
Labels: new-release

#815 PB-471 : add floating mode for tooltip
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/FeatureListCategory.vue
  src/modules/infobox/components/FeatureListCategoryItem.vue
  src/modules/map/components/LocationPopup.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/map/components/openlayers/OpenLayersPopover.vue
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
  src/scss/exports.js
  src/scss/variables.module.scss
  src/setup-fontawesome.js
  src/store/modules/position.store.js
  src/utils/components/SimpleWindow.vue
  src/utils/composables/useMovableElement.composable.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#857 PB-518: Removed time slider on 3D view
  src/views/MapView.vue
Labels: bug

#847 PB-506 : embed sends information to parent about selected features
  src/api/iframeFeatureEvent.api.js
  src/store/plugins/click-on-map-management.plugin.js
  src/views/EmbedView.vue
Labels: feature

#860 PB-505: Added error when external WMTS layer don't support WGS84
  src/api/layers/AbstractLayer.class.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/addImageryLayer-mixins.js
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/store/modules/layers.store.js
  src/store/plugins/external-layers.plugin.js
  src/store/plugins/load-geojson-style-and-data.plugin.js
  src/store/plugins/load-gpx-data.plugin.js
  src/store/plugins/load-kml-data.plugin.js
Labels: feature

#863 PB-506 : send feature event regardless of embed mode
  src/store/modules/features.store.js
  src/views/EmbedView.vue
Labels: feature

#846 PB-501 Show dropdown for year selection in the time slider on tablet screens
  src/modules/i18n/locales/en.json
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderButton.vue
  src/modules/map/components/toolbox/TimeSliderDropdown.vue
  src/modules/map/components/toolbox/TimeSliderDropdownSearchList.vue
  src/modules/map/components/toolbox/useRangeTippy.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: feature

#867 PB-471 : fix 3D location popup
  src/modules/map/components/cesium/CesiumPopover.vue
Labels: bug

#864 PB-521: fix geolocation tracking, zindex and accuracy and several geolocation improvements
  src/modules/map/components/common/mouse-click.composable.js
  src/modules/map/components/common/z-index.composable.js
  src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
  src/store/modules/geolocation.store.js
  src/store/plugins/geolocation-management.plugin.js
Labels: bug

#871 PB-555 : fix too many resolutions being filtered out with WMTS layers
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/utils/layerUtils.js
Labels: bug

#874 PB-521 : add geolocation feedback on Cesium
  src/modules/map/components/cesium/CesiumGeolocationFeedback.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
  src/utils/styleUtils.js
Labels: feature

#877 PB-568 : guard against empty KML feature coordinate
  src/utils/kmlUtils.js
Labels: bug

#875 PB-538 : split profile too long for backend into chunks
  src/api/__tests__/profile.api.spec.js
  src/api/profile/ElevationProfilePoint.class.js
  src/api/profile/profile.api.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#841 PB-490: move 3d zoom buttons to right toolbox
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumToolbox.vue
  src/modules/map/components/toolbox/MapToolbox.vue
  src/modules/map/components/toolbox/ZoomButtons.vue
Labels: feature

#876 PB-228 : add aggregate layer support to 3D
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
Labels: feature

#872 PB-543 : fix Cesium CSS spillover
  src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/toolbox/ZoomButtons.vue
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#862 PB-472 : profile in the context of the new floating tooltip
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureCombo.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfileInformation.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureList.vue
  src/setup-fontawesome.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#878 New Release v1.21.0 - #minor
  src/api/__tests__/profile.api.spec.js
  src/api/profile/ElevationProfilePoint.class.js
  src/api/profile/profile.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureCombo.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfileInformation.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
  src/modules/map/components/cesium/CesiumGeolocationFeedback.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumToolbox.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersAccuracyCircle.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/modules/map/components/toolbox/MapToolbox.vue
  src/modules/map/components/toolbox/ZoomButtons.vue
  src/modules/menu/components/search/SearchBar.vue
  src/setup-fontawesome.js
  src/utils/kmlUtils.js
  src/utils/layerUtils.js
  src/utils/styleUtils.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: new-release
