Repository geoadmin/web-mapviewer, pull requests merged in 2024-09, with the labels that each got.

#1022 PB-154: Geolocation device orientation (gyroscope) - #minor
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/openlayers/OpenLayersCompassButton.vue
  src/modules/map/components/openlayers/OpenLayersGeolocationFeedback.vue
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/OpenLayersMarker.vue
  src/modules/map/components/openlayers/OpenLayersVisionCone.vue
  src/modules/map/components/openlayers/debug/OpenLayersDeviceOrientationDebugInfo.vue
  src/modules/map/components/openlayers/utils/useDeviceOrientation.composable.js
  src/modules/map/components/openlayers/utils/useViewBasedOnProjection.composable.js
  src/modules/map/components/toolbox/GeolocButton.vue
  src/modules/map/components/toolbox/MapToolbox.vue
  src/modules/map/scss/toolbox-buttons.scss
  src/modules/menu/components/debug/DebugToolbar.vue
  src/modules/menu/components/debug/Toggle3DLayerButton.vue
  src/setup-fontawesome.js
  src/store/modules/__tests__/rotation.store.spec.js
  src/store/modules/geolocation.store.js
  src/store/modules/position.store.js
  src/store/plugins/2d-to-3d-management.plugin.js
  src/store/plugins/geolocation-management.plugin.js
  src/store/plugins/sync-camera-lonlatzoom.js
  src/utils/numberUtils.js
  tests/cypress/tests-e2e/toolboxRight.cy.js
Labels: feature

#1048 PB-131 : fix WebMercator extent/bounds
  src/utils/coordinates/WebMercatorCoordinateSystem.class.js
Labels: bug

#1049 PB-865 : remove forced clampToGround for KML polyline in 3D
  src/modules/map/components/cesium/CesiumKMLLayer.vue
Labels: bug

#1046 PB-871 : only dispatch if something has changed
  src/config/baseUrl.config.js
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/menu/components/debug/BaseUrlOverrideModal.vue
  src/router/storeSync/BaseUrlOverrideParamConfig.class.js
Labels: bug

#1057 Keep i18n file key alphabetically sorted
  scripts/generate-i18n-files.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: feature

#1044 PB-843 : use LV03 to LV95 reframe services
  src/api/lv03Reframe.api.js
  src/modules/map/components/LocationPopupPosition.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/utils/__tests__/extentUtils.spec.js
  src/utils/coordinates/__test__/coordinateExtractors.spec.js
  src/utils/coordinates/__test__/coordinateUtils.spec.js
  src/utils/coordinates/coordinateExtractors.js
  src/utils/coordinates/coordinateUtils.js
  src/utils/militaryGridProjection.js
  tests/cypress/tests-e2e/search/coordinates-search.cy.js
Labels: bug

#1028 PB-788 : Mobile/tablet help menu section
  src/modules/i18n/components/LangButton.vue
  src/modules/i18n/components/LangSwitchToolbar.vue
  src/modules/menu/components/header/HeaderLangSelector.vue
  src/modules/menu/components/header/HeaderLink.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/help/HelpLink.vue
  src/modules/menu/components/help/MenuHelpSection.vue
  src/modules/menu/components/help/MoreInfo.vue
  src/modules/menu/components/help/ReportProblemButton.vue
  src/modules/menu/components/help/common/SendActionButtons.vue
  src/modules/menu/components/help/feedback/FeedbackButton.vue
  src/modules/menu/components/help/feedback/FeedbackRating.vue
  src/modules/menu/components/menu/MenuSection.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/modules/menu/components/settings/LinksToolbar.vue
  src/modules/menu/components/settings/MenuSettings.vue
  src/modules/menu/components/settings/MoreInfo.vue
  src/modules/menu/components/share/MenuShareSection.vue
  src/modules/menu/components/topics/MenuTopicSection.vue
  src/scss/webmapviewer-bootstrap-theme.scss
  src/utils/components/AppVersion.vue
  src/views/MapView.vue
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/feedback.cy.js
  tests/cypress/tests-e2e/header.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/menuTray.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: bug

#1061 PB-977: Don't use service-proxy for internal domain and for GPX that support CORS - #patch
  src/api/file-proxy.api.js
  src/api/files.api.js
  src/config/baseUrl.config.js
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
  src/store/plugins/load-gpx-data.plugin.js
  src/utils/kmlUtils.js
  src/utils/utils.js
  tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1015 PB-818: Ensuring scales are respected on print - #minor
  src/api/__tests__/print.api.spec.js
  src/api/print.api.js
  src/config/print.config.js
  src/utils/styleUtils.js
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#1017 PB-804 : don't center on search query when sharing position - #minor
  src/App.vue
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/router/storeSync/CrossHairParamConfig.class.js
  src/router/storeSync/SearchParamConfig.class.js
  src/router/storeSync/abstractParamConfig.class.js
  src/router/storeSync/storeSync.config.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/search.store.js
  src/store/modules/ui.store.js
  src/store/plugins/geolocation-management.plugin.js
  src/store/plugins/redo-search-when-needed.plugin.js
  src/utils/ErrorMessage.class.js
Labels: bug

#1058 PB-66: Add new babs icons to mapviewer
  src/api/icon.api.js
  src/modules/i18n/index.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/utils/components/DropdownButton.vue
  src/utils/composables/useTippyTooltip.js
  src/utils/kmlUtils.js
  tests/cypress/fixtures/service-icons/set-babs.fixture.json
  tests/cypress/fixtures/service-icons/sets.fixture.json
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#1065 PB-984: implement an error queue
  src/App.vue
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/router/storeSync/CrossHairParamConfig.class.js
  src/store/modules/ui.store.js
  src/store/plugins/geolocation-management.plugin.js
Labels: feature

#1068 PB-1006: Fixed CORS issue with admin.ch hosts
  src/config/baseUrl.config.js
Labels: bug

#1069 PB-1007: fix doubling of length value
  src/utils/geodesicManager.js
Labels: bug

#1070 New Release v1.47.1 - #patch
  src/config/baseUrl.config.js
  src/utils/geodesicManager.js
Labels: new-release

#1066 PB-1000 : add support for local GeoTIFF import
  package-lock.json
  package.json
  src/api/layers/GeoTIFFLayer.class.js
  src/api/layers/LayerTypes.enum.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/openlayers/OpenLayersGeoTIFF.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
  src/modules/menu/components/advancedTools/ImportFile/utils.js
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/layers.store.js
  src/utils/components/FileInput.vue
  src/utils/utils.js
Labels: feature

#1072 PB-896 : show un-simplified GPX track
  package-lock.json
  package.json
  src/modules/infobox/components/ShowGeometryProfileButton.vue
  src/store/modules/features.store.js
  src/utils/gpxUtils.js
Labels: bug

#1073 PB-1017: un-proxy external graphics in print specs
  src/api/file-proxy.api.js
  src/api/print.api.js
Labels: bug

#1075 PB-960: handle long press events error on some mobiles
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Labels: bug

#1081 PB-1017 : use of camelCase (and not snake_case)
  src/api/file-proxy.api.js
Labels: bug

#1077 PB-1031: link for more informations changed
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: feature

#1060 PB-900: Add no shared icon and text
  src/modules/map/components/footer/MapFooterAttributionList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/share/MenuShareEmbed.vue
  src/scss/tippy-theme.scss
  src/setup-fontawesome.js
  src/store/modules/layers.store.js
  src/utils/components/ThirdPartyDisclaimer.vue
  tests/cypress/tests-e2e/importToolFile.cy.js
  tests/cypress/tests-e2e/importToolMaps.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/shareShortLink.cy.js
Labels: feature

#1052 PB-912 Fix language of background layer attribution
  src/modules/map/components/common/z-index.composable.js
  src/modules/map/components/footer/MapFooterAttributionList.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelector.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
  src/modules/map/components/footer/backgroundSelector/BackgroundSelectorWheelRounded.vue
  src/modules/map/components/openlayers/OpenLayersBackgroundLayer.vue
  src/modules/map/components/openlayers/debug/OpenLayersLayerExtents.vue
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/router/storeSync/storeSync.config.js
  src/store/modules/__tests__/layers.store.spec.js
  src/store/modules/cesium.store.js
  src/store/modules/layers.store.js
  src/store/plugins/topic-change-management.plugin.js
  src/utils/legacyLayerParamUtils.js
  tests/cypress/tests-e2e/footer.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/topics.cy.js
Labels: feature
