Repository geoadmin/web-mapviewer, pull requests merged in 2024-12, with the labels that each got.

#1151 PB-1259: allow bgLayer modification through URL
  src/router/storeSync/storeSync.config.js
  src/store/modules/layers.store.js
Labels: bug

#1152 New Release v1.49.2 - #patch
  src/api/layers/ExternalWMTSLayer.class.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumVisibleLayers.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/useAddImageryLayer.composable.js
  src/modules/menu/components/help/MoreInfo.vue
  src/router/storeSync/storeSync.config.js
  src/store/modules/layers.store.js
  src/store/plugins/sync-camera-lonlatzoom.js
  tests/cypress/fixtures/layers.fixture.json
  tests/cypress/tests-e2e/3d/layers.cy.js
  tests/cypress/tests-e2e/header.cy.js
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: new-release

#1154 New Release v1.49.3 - #patch
  src/router/legacyPermalinkManagement.routerPlugin.js
Labels: new-release

#1159 PB-1254: fix embed preview in chrome
  src/router/storeSync/storeSync.config.js
  tests/cypress/tests-e2e/embed.cy.js
Labels: bug

#1160 PB-1181: menu scrollable
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/menu/MenuTray.vue
  tests/cypress/tests-e2e/importToolMaps.cy.js
  tests/cypress/tests-e2e/menuTray.cy.js
Labels: feature

#1163 PB-1246 : add location search entry title to search bar when selected
  src/store/modules/search.store.js
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: bug

#1164 PB-1176: Fix cesium static assets location
  .eslintrc.cjs
  src/config/map.config.js
  src/modules/map/components/cesium/CesiumMap.vue
  vite.config.mts
Labels: feature

#1166 PB-1146: Zoom in on geolocation first activation
  src/store/plugins/geolocation-management.plugin.js
Labels: bug

#1168 PB-1290 : read time slider oldest/youngest year from layers config
  src/config/time.config.js
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderDropdown.vue
  src/modules/map/components/toolbox/TimeSliderDropdownSearchList.vue
  src/router/storeSync/TimeSliderParamConfig.class.js
  src/store/modules/layers.store.js
  tests/cypress/fixtures/layers.fixture.json
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: bug

#1148 PB-1204 Cesium WMS as composable and tested with Cypress
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/utils/useAddImageryLayer.composable.js
  src/modules/menu/components/LayerCatalogueItem.vue
  tests/cypress/tests-e2e/3d/layers.cy.js
  tests/cypress/tests-e2e/importToolFile.cy.js
Labels: feature

#1171 PB-1150 : increase Cypress memory
  cypress.config.mjs
  src/modules/map/components/CompareSlider.vue
  tests/cypress/tests-e2e/compareSlider.cy.js
Labels: feature

#1172 PB-1295 : add drag&drop support for 3D viewer
  src/modules/map/components/cesium/CesiumInteractions.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/common/useDragFileOverlay.composable.js
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Labels: bug

#1157 PB-1176: Prepare build output for CD Pipeline
  package-lock.json
  package.json
  vite-plugins/vite-plugin-generate-build-info.js
  vite.config.mts
Labels: feature

#1176 PB-1301 : migration to Node22 and update libs
  package-lock.json
  package.json
Labels: feature

#1169 PB-1223: add test more information feature info
  tests/cypress/fixtures/html-popup.fixture.html
  tests/cypress/fixtures/infobox.fixture.html
  tests/cypress/tests-e2e/infobox.cy.js
Labels: feature
