Repository geoadmin/web-mapviewer, pull requests merged in 2024-06, with the labels that each got.

#882 PB-521: Enabled geolocation high accuracy
  src/store/plugins/geolocation-management.plugin.js
Labels: bug

#879 PB-574: Fix layers parameter issue at startup
  src/router/storeSync/LayerParamConfig.class.js
Labels: bug

#865 PB-534: transparency slider works in real time
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
Labels: bug

#884 PB-562 : do not force drawing module's style onto external KMLs
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/kmlUtils.js
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#885 PB-591 : 3D KML improvements
  src/modules/map/components/cesium/CesiumKMLLayer.vue
Labels: bug

#881 PB-548 : fix camera position present in URL at startup issue
  src/modules/map/components/cesium/CesiumMap.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/PositionParamConfig.class.js
  src/router/storeSync/ZoomParamConfig.class.js
  src/store/plugins/sync-camera-lonlatzoom.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#883 PB-575: Html popup tooltip issues
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/toolbox/TimeSlider.vue
  src/scss/exports.js
  src/scss/variables.module.scss
  src/utils/geoJsonUtils.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: bug

#890 PB517, PB-588: Fixed legacy X/Y parameter in LV03 and LV95
  src/router/legacyPermalinkManagement.routerPlugin.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#887 PB-583 : use backend service to get LV03 <> LV95 conversion right
  src/api/lv03Reframe.api.js
  src/modules/map/components/LocationPopupPosition.vue
  src/utils/components/CoordinateCopySlot.vue
  tests/cypress/tests-e2e/mouseposition.cy.js
Labels: feature

#891 New Release v1.22.0 - #minor
  src/api/lv03Reframe.api.js
  src/modules/map/components/LocationPopupPosition.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/PositionParamConfig.class.js
  src/router/storeSync/ZoomParamConfig.class.js
  src/scss/exports.js
  src/scss/variables.module.scss
  src/store/plugins/geolocation-management.plugin.js
  src/store/plugins/sync-camera-lonlatzoom.js
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/components/CoordinateCopySlot.vue
  src/utils/geoJsonUtils.js
  src/utils/kmlUtils.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
  tests/cypress/tests-e2e/mouseposition.cy.js
  tests/cypress/tests-e2e/print.cy.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: new-release

#892 PB-607: Fix drawing share URL: use full query params in share url
  src/modules/drawing/components/SharePopup.vue
Labels: bug

#894 Fix tooltip movable window pointer and icon issues
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/utils/composables/useMovableElement.composable.js
Labels: bug

#893 PB-449: Add a minimize button to give feedback and report problem
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/modules/menu/components/settings/feedback/FeedbackButton.vue
  src/store/modules/ui.store.js
  src/utils/components/SimpleWindow.vue
  tests/cypress/tests-e2e/feedback.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: feature

#902 PB-588 : revert changes made to E and N in legacy parser
  src/router/legacyPermalinkManagement.routerPlugin.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#897 PB-621: Fixed default lang with `-CH` suffix
  src/modules/i18n/index.js
  src/store/modules/i18n.store.js
Labels: bug

#900 PB-570 : use service-proxy for failed KML/GPX URL import
  .env.development
  .env.integration
  .env.production
  src/api/__tests__/file-proxy.api.spec.js
  src/api/file-proxy.api.js
  src/config.js
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
Labels: feature

#895 Add title to infobox
  src/modules/infobox/InfoboxModule.vue
  src/utils/components/ZoomToExtentButton.vue
Labels: bug

#903 New Release v1.23.0 - #minor
  .env.development
  .env.integration
  .env.production
  src/api/__tests__/file-proxy.api.spec.js
  src/api/file-proxy.api.js
  src/config.js
  src/modules/drawing/components/SharePopup.vue
  src/modules/i18n/index.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/InfoboxModule.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/modules/menu/components/settings/feedback/FeedbackButton.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/store/modules/i18n.store.js
  src/store/modules/ui.store.js
  src/utils/components/SimpleWindow.vue
  src/utils/components/ZoomToExtentButton.vue
  src/utils/composables/useMovableElement.composable.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/feedback.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: new-release

#904 PB-542 : take into account "config3d" layers config property
  src/api/layers/GeoAdminLayer.class.js
  src/api/layers/GeoAdminWMSLayer.class.js
  src/api/layers/GeoAdminWMTSLayer.class.js
  src/api/layers/layers.api.js
  src/modules/map/components/cesium/CesiumMap.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/store/modules/cesium.store.js
  src/store/modules/layers.store.js
  src/store/plugins/2d-to-3d-management.plugin.js
  src/store/plugins/load-layersconfig-on-lang-change.js
  tests/cypress/fixtures/layers.fixture.json
  tests/cypress/tests-e2e/footer.cy.js
Labels: bug

#907 PB-621 : fix issue where lang can't be changed anymore
  src/modules/i18n/index.js
  src/store/modules/i18n.store.js
Labels: bug

#886 PB-589 : limit WMS request to LV95 extent
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
Labels: bug

#898 PB-622: Fix timed layer with only one timestamps
  src/api/layers/layers.api.js
Labels: bug

#880 PB-494: Add address bar on 3D map
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumMouseTracker.vue
  src/store/modules/cesium.store.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/views/MapView.vue
Labels: bug

#911 PB-546: Put print overlay always on top
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/modules/menu/components/settings/HelpLink.vue
Labels: bug

#912 PB-639 : prevent parsing of non legacy layers URL param
  src/router/legacyPermalinkManagement.routerPlugin.js
Labels: bug

#913 PB-570 : also proxy KML loaded at startup
  src/api/files.api.js
Labels: bug

#915 PB-546: Put print overlay always on top
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
Labels: bug

#917 New Release v1.25.0 - #minor
  src/api/files.api.js
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumMouseTracker.vue
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/store/modules/cesium.store.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/views/MapView.vue
Labels: new-release

#910 Updated the help link to the new help from the goe.admin.ch CMS
  src/modules/menu/components/settings/HelpLink.vue
Labels: feature

#918 New Release v1.26.0 - #minor
  src/modules/menu/components/settings/HelpLink.vue
Labels: new-release

#922 PB-637: Keep time layer selected year when changing the language
  src/store/modules/layers.store.js
  tests/cypress/tests-e2e/layers.cy.js
Labels: bug

#916 PB-546: Print overlay not centered on high resolution device (e.g. Retina or HiDPI device)
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
Labels: bug

#921 Fix uncaught exception when using drag selection
  src/modules/map/components/openlayers/OpenLayersRectangleSelectionFeedback.vue
Labels: bug

#920 PB-633: Fix map panning being too fast
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
Labels: bug

#919 PB-546: Improved default print scale computed from map size
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#888 PB-587: altering feature info behavior on mobile
  src/config.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/map/components/MapPopover.vue
  src/store/modules/ui.store.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/featureSelection.cy.js
  tests/cypress/tests-e2e/infobox.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#923 New Release v1.27.0 - #minor
  src/config.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/openlayers/OpenLayersRectangleSelectionFeedback.vue
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/store/modules/layers.store.js
  src/store/modules/ui.store.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/featureSelection.cy.js
  tests/cypress/tests-e2e/infobox.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
  tests/cypress/tests-e2e/print.cy.js
Labels: new-release

#924 Try solve test flakiness introduced by #922
  tests/cypress/tests-e2e/layers.cy.js
Labels: bug

#929 PB-660: Fix elevation profile resize
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
Labels: bug

#926 PB-647: Fix CSS non link attribution
  src/modules/map/components/footer/MapFooterAttributionItem.vue
Labels: bug

#928 PB-643: Implement left/right key press to move time slider
  index.html
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderButton.vue
Labels: bug

#931 New Release v1.28.0 - #minor
  README.md
  ROADMAP.md
  index.html
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/map/components/cesium/CesiumGPXLayer.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/footer/MapFooterAttributionItem.vue
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderButton.vue
  tests/cypress/tests-e2e/layers.cy.js
Labels: new-release

#901 PB-586 improve tooltip css
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureListCategory.vue
  src/modules/infobox/components/FeatureListCategoryItem.vue
Labels: bug

#927 PB-585: make tooltip reactive to language change
  src/modules/infobox/components/FeatureList.vue
  src/store/modules/features.store.js
Labels: bug

#905 PB-412: Update print to use native print inside a modal for Infobox, Map-Popover and Legend
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureListCategory.vue
  src/modules/infobox/components/InfoboxContent.vue
  src/modules/infobox/components/ShowGeometryProfileButton.vue
  src/modules/map/components/MapPopover.vue
  src/scss/main.scss
  src/utils/components/ModalPrintWithBackdrop.vue
  src/utils/components/ModalWithBackdrop.vue
  src/utils/components/PrintButton.vue
  src/utils/print.js
  src/views/EmbedView.vue
  src/views/MapView.vue
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#932 PB-646: Fix logic to set value in style from literal.
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
Labels: bug

#936 PB-662 : disable opacity slider for KML/GPX on 3D
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
Labels: bug

#934 PB-630 : removing extra LV95 zoom level
  src/utils/coordinates/SwissCoordinateSystem.class.js
Labels: bug

#933 PB-634: Fix feature selection of layer "Moorlandschaften AuLaV"
  src/api/features/features.api.js
  src/router/storeSync/LayerParamConfig.class.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: bug

#938 New Release v1.29.0 - #minor
  src/api/features/features.api.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/FeatureListCategory.vue
  src/modules/infobox/components/FeatureListCategoryItem.vue
  src/modules/infobox/components/InfoboxContent.vue
  src/modules/infobox/components/ShowGeometryProfileButton.vue
  src/modules/map/components/MapPopover.vue
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/scss/main.scss
  src/store/modules/features.store.js
  src/utils/components/ModalPrintWithBackdrop.vue
  src/utils/components/ModalWithBackdrop.vue
  src/utils/components/PrintButton.vue
  src/utils/coordinates/SwissCoordinateSystem.class.js
  src/utils/identifyOnVectorLayer.js
  src/utils/print.js
  src/views/EmbedView.vue
  src/views/MapView.vue
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: new-release

#941 Fix default opacity for external WMS/WMTS layer
  src/router/storeSync/LayerParamConfig.class.js
Labels: bug

#939 PB-590: Quick fix for timeslider preview year for layer without current year entry
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/store/modules/layers.store.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: bug

#943 Fix time selector button CSS
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/modules/menu/components/common/MenuItemCheckBox.vue
  src/modules/menu/scss/menu-items.scss
Labels: bug

#945 New Release v1.30.0 - #minor
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/modules/menu/components/common/MenuItemCheckBox.vue
  src/modules/menu/scss/menu-items.scss
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/layers.store.js
  src/utils/featureStyleUtils.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: new-release

#944 PB-669 : separate html popup request from getFeature
  src/api/features/features.api.js
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/features.store.js
  tests/cypress/fixtures/features/features.fixture.json
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: feature

#946 PB-681 : add support for group of external layers getFeatureInfo
  src/api/features/features.api.js
Labels: bug

#942 PB-675: Clean up TimeSlider code
  src/api/features/features.api.js
  src/api/layers/LayerTimeConfig.class.js
  src/api/layers/LayerTimeConfigEntry.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/layers/layers.api.js
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderButton.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/router/storeSync/layersParamParser.js
  src/store/modules/layers.store.js
  src/utils/kmlUtils.js
  src/utils/layerUtils.js
  src/utils/legacyLayerParamUtils.js
  tests/cypress/tests-e2e/featureSelection.cy.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: bug

#947 New Release v1.31.0 - #minor
  src/api/features/features.api.js
  src/api/layers/LayerTimeConfig.class.js
  src/api/layers/LayerTimeConfigEntry.class.js
  src/api/layers/WMSCapabilitiesParser.class.js
  src/api/layers/layers.api.js
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumWMSLayer.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersExternalWMTSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  src/modules/map/components/toolbox/TimeSlider.vue
  src/modules/map/components/toolbox/TimeSliderButton.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/router/storeSync/layersParamParser.js
  src/store/modules/features.store.js
  src/store/modules/layers.store.js
  src/utils/kmlUtils.js
  src/utils/layerUtils.js
  src/utils/legacyLayerParamUtils.js
  tests/cypress/fixtures/features/features.fixture.json
  tests/cypress/tests-e2e/featureSelection.cy.js
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: new-release

#937 PB-645: zoom to extent on feature preselection
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/store/plugins/geolocation-management.plugin.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/utils/coordinates/StandardCoordinateSystem.class.js
  src/utils/coordinates/SwissCoordinateSystem.class.js
  tests/cypress/tests-e2e/search/coordinates-search.cy.js
Labels: bug

#949 PB-698 : updating translations
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: feature

#948 New Release v1.32.0 - #minor
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/position.store.js
  src/store/modules/search.store.js
  src/store/plugins/geolocation-management.plugin.js
  src/utils/coordinates/CoordinateSystem.class.js
  src/utils/coordinates/StandardCoordinateSystem.class.js
  src/utils/coordinates/SwissCoordinateSystem.class.js
  tests/cypress/tests-e2e/search/coordinates-search.cy.js
Labels: new-release

#950 Improve geolocation error management by removing the alert() - #patch
  src/App.vue
  src/modules/map/components/toolbox/GeolocButton.vue
  src/store/modules/ui.store.js
  src/store/plugins/geolocation-management.plugin.js
  src/utils/components/ErrorWindow.vue
  tests/cypress/tests-e2e/geolocation.cy.js
Labels: bug

#953 PB-703: Fix /index.html share embed - #patch
  src/utils/__tests__/utils.spec.js
  src/utils/utils.js
Labels: bug

#954 Display also the version on prod staging - #patch
  src/modules/map/components/footer/MapFooterAppVersion.vue
Labels: feature

#958 PB-707 : show tooltip on iframe - #patch
  src/store/plugins/click-on-map-management.plugin.js
Labels: bug

#959 PB-709 : also change 3D specific config timestamp - #patch
  src/store/modules/layers.store.js
Labels: bug

#961 PB-713: revert to use the same logic as in the old geoadmin. - #patch
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
Labels: bug

#963 PB-717 : add current year to time slider years - #patch
  src/config.js
Labels: bug

#962 PB-716 : guess WGS84 coordinate order in the searchbar - #patch
  src/utils/coordinates/__test__/coordinateExtractors.spec.js
  src/utils/coordinates/coordinateExtractors.js
  tests/cypress/tests-e2e/search/coordinates-search.cy.js
Labels: bug

#966 PB-720: Fix default language detection - #patch
  src/modules/i18n/index.js
Labels: bug

#957 PB-387: Fix geolocation outside switzerland - #patch
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/store/modules/position.store.js
  src/store/plugins/geolocation-management.plugin.js
  src/utils/components/ErrorWindow.vue
  tests/cypress/tests-e2e/3d/navigation.cy.js
Labels: bug

#971 PB-734 : search all layers with ID before fallback to technical name - #patch
  src/api/topics.api.js
Labels: bug

#967 PB-726: Added a print progress bar instead of a spinner - #patch
  src/modules/menu/components/print/MenuPrintSection.vue
  src/utils/components/ProgressBar.vue
  tests/cypress/tests-e2e/3d/navigation.cy.js
Labels: feature

#968 PB-742: Use permalink on report problem email - #patch
  src/api/feedback.api.js
Labels: bug

#955 PB-186: pre processing tool for URL parameters - #minor
  src/router/legacyPermalinkManagement.routerPlugin.js
Labels: feature
