Repository geoadmin/web-mapviewer, pull requests merged in 2024-02, with the labels that each got.

#626 PB-101 : zoom on GPX extent on file added
  package-lock.json
  package.json
  src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
  src/modules/menu/components/advancedTools/ImportFile/utils.js
  src/store/modules/layers.store.js
  src/utils/__tests__/extentUtils.spec.js
  src/utils/__tests__/gpxUtils.spec.js
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/coordinates/coordinateUtils.js
  src/utils/extentUtils.js
  src/utils/gpxUtils.js
  src/utils/kmlUtils.js
Labels: feature

#629 PB-114: Removed `editableFeature` from KML output
  src/api/__tests__/features.api.spec.js
  src/api/features.api.js
  src/api/icon.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/README.md
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/components/SharePopup.vue
  src/modules/drawing/components/useDrawingModeInteraction.composable.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/components/FeatureCombo.vue
  src/modules/infobox/components/FeatureEdit.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/featureStyleUtils.js
  src/utils/geodesicManager.js
  src/utils/identifyOnVectorLayer.js
  src/utils/kmlUtils.js
  src/utils/legacyKmlUtils.js
  src/utils/utils.js
  tests/cypress/fixtures/service-kml/lonelyMarker.kml
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#630 PB-114: Moved utils out of drawing modules
  src/api/features.api.js
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/drawing/components/useDrawingModeInteraction.composable.js
  src/modules/drawing/components/useModifyInteraction.composable.js
  src/modules/drawing/lib/__tests__/drawingUtils.spec.js
  src/modules/drawing/lib/drawingUtils.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/style.js
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureElevationProfileInformation.vue
  src/modules/infobox/components/styling/SelectedFeatureProfile.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/utils/__tests__/utils.spec.js
  src/utils/coordinates/__test__/coordinateUtils.spec.js
  src/utils/coordinates/coordinateUtils.js
  src/utils/featureStyleUtils.js
  src/utils/geodesicManager.js
  src/utils/kmlUtils.js
  src/utils/utils.js
  tests/cypress/tests-e2e/geodesicDrawing.cy.js
Labels: feature

#631 PB-114: Added kml utils unit tests and fix small edge case issues
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/kmlUtils.js
Labels: feature

#632 PB-267: Removed adminId guard on non prod hosts
  src/config.js
  src/modules/drawing/DrawingModule.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/router/legacyPermalinkManagement.routerPlugin.js
  src/utils/kmlUtils.js
  tests/cypress/fixtures/service-icons/set-default.fixture.json
  tests/cypress/fixtures/service-kml/legacy-mf-geoadmin3.kml
  tests/cypress/support/commands.js
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#633 PB-101 : add support for GPX reloading and e2e tests
  src/modules/drawing/useKmlDataManagement.composable.js
  src/modules/menu/components/advancedTools/ImportFile/utils.js
  src/router/storeSync/LayerParamConfig.class.js
  src/store/index.js
  src/store/modules/layers.store.js
  src/store/plugins/load-gpx-data.plugin.js
  src/store/plugins/load-kml-data.plugin.js
  src/utils/gpxUtils.js
  tests/cypress/fixtures/import-tool/external-gpx-file.gpx
  tests/cypress/tests-e2e/importToolFile.cy.js
Labels: feature

#621 PB-99: Added Print Map UI
  src/api/print.api.js
  src/modules/map/components/openlayers/OpenLayersMap.vue
  src/modules/map/components/openlayers/utils/print-area-renderer.composable.js
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/store/modules/print.store.js
  src/store/modules/ui.store.js
Labels: feature

#628 PB-266: Added ADR about drawing text and icon size
  adr/2024_01_31_drawing_icon_size.md
Labels: feature

#640 PB-248: Fix Clipboard update issue for position popup
  src/modules/map/components/LocationPopupCopySlot.vue
Labels: feature

#617 PB-203: Debounce edit text dispatch
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  tests/cypress/fixtures/3d/terrain-3d-layer.json
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/3d/layers.cy.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#643 Fix cypress e2e 3d tests
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/3d/layers.cy.js
  tests/cypress/tests-e2e/3d/navigation.cy.js
Labels: bug

#641 PB-266: Corrected KML icons size
  src/api/features.api.js
  src/api/icon.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/utils/__tests__/kmlUtils.spec.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/featureStyleUtils.js
  src/utils/kmlUtils.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#636 PB-269 : GPX/KML generic feature identification
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/features.api.js
  src/api/features/EditableFeature.class.js
  src/api/features/LayerFeature.class.js
  src/api/features/SelectableFeature.class.js
  src/api/features/features.api.js
  src/modules/drawing/README.md
  src/modules/drawing/components/DrawingInteractions.vue
  src/modules/drawing/components/DrawingLineInteraction.vue
  src/modules/drawing/components/DrawingMarkerInteraction.vue
  src/modules/drawing/components/DrawingMeasureInteraction.vue
  src/modules/drawing/components/DrawingTextInteraction.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/DrawingToolboxButton.vue
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/components/useDrawingLineInteraction.composable.js
  src/modules/drawing/components/useDrawingModeInteraction.composable.js
  src/modules/drawing/components/useModifyInteraction.composable.js
  src/modules/drawing/useKmlDataManagement.composable.js
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureCombo.vue
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureEdit.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/infobox/components/styling/SelectedFeatureProfile.vue
  src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/common/mouse-click.composable.js
  src/modules/map/components/openlayers/OpenLayersGeoJSONLayer.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/map/components/openlayers/OpenLayersMarker.vue
  src/modules/map/components/openlayers/utils/add-vector-layer-to-map.composable.js
  src/store/README.md
  src/store/modules/drawing.store.js
  src/store/modules/features.store.js
  src/store/plugins/click-on-map-management.plugin.js
  src/store/plugins/reproject-selected-features-on-projection-change.plugin.js
  src/utils/__tests__/legacyKmlUtils.spec.js
  src/utils/featureStyleUtils.js
  src/utils/geoJsonUtils.js
  src/utils/identifyOnVectorLayer.js
  src/utils/kmlUtils.js
  src/views/MapView.vue
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/3d/layers.cy.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/geodesicDrawing.cy.js
Labels: feature

#647 Added menu advanced tool on prod and remove print menu on prod
  src/modules/menu/components/menu/MenuTray.vue
Labels: feature

#646 Avoid error log during language change
  src/modules/menu/components/advancedTools/ImportCatalogue/ProviderUrl.vue
Labels: bug

#649 Fix race condition when exporting/saving kml
  adr/2024_01_31_drawing_icon_size.md
  src/api/features/EditableFeature.class.js
  src/api/icon.api.js
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#650 Fix error on prod when debug store module is absent
  src/store/index.js
Labels: bug

#639 PB-123 : Change color of hovered feature
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/WarningRibbon.vue
  src/modules/map/components/footer/MapFooterAppCopyright.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/map/components/openlayers/utils/markerStyle.js
  src/scss/variables-admin.module.scss
  src/scss/webmapviewer-bootstrap-theme.scss
  src/store/modules/features.store.js
Labels: feature

#651 New Release v1.6.0 - #minor
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/WarningRibbon.vue
  src/modules/map/components/footer/MapFooterAppCopyright.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/map/components/openlayers/utils/markerStyle.js
  src/scss/variables-admin.module.scss
  src/scss/webmapviewer-bootstrap-theme.scss
  src/store/index.js
  src/store/modules/features.store.js
Labels: new-release

#652 PB-293: Corrected external layer order at startup and improve a bit performance
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/layers.store.js
  src/store/plugins/external-layers.plugin.js
  src/store/plugins/load-geojson-style-and-data.plugin.js
  src/store/plugins/load-gpx-data.plugin.js
  src/store/plugins/load-kml-data.plugin.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
Labels: bug

#645 PB-259: Added best practices docu
  README.md
  src/store/README.md
Labels: feature

#653 PB-238 : drag&drop reordering of active layers
  package-lock.json
  package.json
  src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
  src/modules/menu/scss/menu-items.scss
  src/store/modules/__tests__/layers.store.spec.js
  src/store/modules/layers.store.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/layers.cy.js
Labels: feature

#654 PB-259: Improve topic parsing at startup
  src/api/topics.api.js
  src/store/plugins/load-layersconfig-on-lang-change.js
Labels: feature

#657 PB-282: Location share Whats App
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
  src/setup-fontawesome.js
  tests/cypress/tests-e2e/mouseposition.cy.js
  tests/cypress/tests-e2e/shareShortLink.cy.js
Labels: feature

#662 Fix Drag&Drop e2e test on CI
  tests/cypress/tests-e2e/layers.cy.js
Labels: bug

#664 PB-259: Converted topic section into composition API
  src/main.js
  src/modules/menu/components/topics/MenuTopicSection.vue
  vite.config.mts
Labels: feature

#663 PB-259: Improve startup performance by rendering menu section only when the map is rendered
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/topics/MenuTopicSection.vue
  src/router/storeSync/storeSync.routerPlugin.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/importToolFile.cy.js
  tests/cypress/tests-e2e/importToolMaps.cy.js
Labels: feature

#667 PB-56: Added other 3D constructions
  src/modules/menu/components/debug/Toggle3DLayerButton.vue
  src/setup-fontawesome.js
  src/store/modules/cesium.store.js
  tests/cypress/tests-e2e/3d/layers.cy.js
Labels: feature

#670 Fix active layers scrolling on touch device
  src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Labels: bug
