Repository geoadmin/web-mapviewer, pull requests merged in 2024-04, with the labels that each got.

#727 PB-111: Fix print spec send to the print service
  package-lock.json
  package.json
  src/api/print.api.js
  src/modules/map/components/openlayers/utils/printConstants.js
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/modules/menu/components/debug/DebugToolbar.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  tests/cypress/fixtures/print/capabilities.json
  tests/cypress/fixtures/print/mapfish-print-report.pdf
  tests/cypress/tests-e2e/print.cy.js
Labels: feature

#753 PB-362: Improved loading bar which can now be used by other components
  src/modules/drawing/DrawingModule.vue
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/store/index.js
  src/store/modules/ui.store.js
  src/store/plugins/app-readiness.plugin.js
  src/store/plugins/load-geojson-style-and-data.plugin.js
  src/store/plugins/loading-bar-management.plugin.js
  src/utils/components/LoadingScreen.vue
  src/views/LegacyParamsView.vue
  src/views/MapView.vue
Labels: feature

#752 PB-374: Removed invalid external providers
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
Labels: feature

#756 New Release v1.13.0 - #minor
  package-lock.json
  package.json
  src/api/layers/layers.api.js
  src/api/print.api.js
  src/api/topics.api.js
  src/modules/drawing/DrawingModule.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/openlayers/utils/printConstants.js
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/modules/map/components/openlayers/utils/usePrintAreaRenderer.composable.js
  src/modules/menu/components/LayerCatalogueItem.vue
  src/modules/menu/components/LayerDescriptionPopup.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
  src/modules/menu/components/advancedTools/ImportCatalogue/useProviders.js
  src/modules/menu/components/debug/DebugToolbar.vue
  src/modules/menu/components/header/HeaderWithSearch.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/modules/menu/components/search/SearchResultCategory.vue
  src/modules/menu/components/search/SearchResultList.vue
  src/modules/menu/components/search/SearchResultListEntry.vue
  src/store/index.js
  src/store/modules/ui.store.js
  src/store/plugins/app-readiness.plugin.js
  src/store/plugins/load-geojson-style-and-data.plugin.js
  src/store/plugins/loading-bar-management.plugin.js
  src/utils/components/LoadingScreen.vue
  src/views/LegacyParamsView.vue
  src/views/MapView.vue
  tests/cypress/fixtures/print/capabilities.json
  tests/cypress/fixtures/print/mapfish-print-report.pdf
  tests/cypress/support/commands.js
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/importToolMaps.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/print.cy.js
  tests/cypress/tests-e2e/search/search-results.cy.js
  tests/cypress/tests-e2e/topics.cy.js
Labels: new-release

#758 PB-111: Update geoblocks/mapfishprint to v0.2.11
  package-lock.json
  package.json
Labels: feature

#762 Fix GPX local file import
  src/api/layers/GPXLayer.class.js
  src/store/plugins/external-layers.plugin.js
  src/store/plugins/load-geojson-style-and-data.plugin.js
  src/store/plugins/load-gpx-data.plugin.js
Labels: bug

#624 PB-239: Add form for reporting problem
  src/api/feedback.api.js
  src/config.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/advancedTools/ImportFile/ImportFileLocalTab.vue
  src/modules/menu/components/menu/common/FeedbackActionButtons.vue
  src/modules/menu/components/menu/feedback/FeedbackButton.vue
  src/modules/menu/components/menu/feedback/FeedbackToolbar.vue
  src/modules/menu/components/menu/reportProblem/ReportProblemButton.vue
  src/store/modules/ui.store.js
  src/utils/components/EmailValidationField.vue
  src/utils/components/ImportLocalFile.vue
  src/utils/utils.js
  tests/cypress/tests-e2e/feedback.cy.js
  tests/cypress/tests-e2e/feedbackTestUtils.js
  tests/cypress/tests-e2e/importToolFile.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: feature

#755 PB-295: CatalogueNodes parameter is now persistent
  src/modules/menu/components/LayerCatalogue.vue
  src/modules/menu/components/LayerCatalogueItem.vue
  src/modules/menu/components/topics/MenuTopicSection.vue
  src/router/storeSync/CameraParamConfig.class.js
  src/router/storeSync/CompareSliderParamConfig.class.js
  src/router/storeSync/CrossHairParamConfig.class.js
  src/router/storeSync/CustomDispatchUrlParamConfig.class.js
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/PositionParamConfig.class.js
  src/router/storeSync/QueryToStoreOnlyParamConfig.class.js
  src/router/storeSync/SimpleUrlParamConfig.class.js
  src/router/storeSync/ZoomParamConfig.class.js
  src/router/storeSync/__tests__/SimpleUrlParamConfig.class.spec.js
  src/router/storeSync/__tests__/abstractParamConfig.class.spec.js
  src/router/storeSync/abstractParamConfig.class.js
  src/router/storeSync/storeSync.config.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/topics.store.js
  src/store/plugins/topic-change-management.plugin.js
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/embed.cy.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
  tests/cypress/tests-e2e/topics.cy.js
Labels: feature

#766 PB-390, PB-391: Change the pdf print file name and fixed print lang parameter
  src/api/print.api.js
  src/modules/map/components/openlayers/utils/usePrint.composable.js
Labels: feature

#768 PB-296: Add failOnError to all layers
  src/api/print.api.js
Labels: feature

#771 PB-397: Temporary change print backend from dev to int due to dev backend issue
  src/api/print.api.js
Labels: feature

#775 PB-358: Fix Complex geometry feature infobox default display
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
Labels: feature

#778 Update project requirement, now needing NPM v10
  package-lock.json
  package.json
Labels: feature

#776 PB-396: Make search result dropdown disappear when going to location
  src/modules/menu/components/search/SearchBar.vue
  src/modules/menu/components/search/SearchResultList.vue
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: feature

#783 Allow newest nodejs version v18
  .nvmrc
Labels: feature

#769 PB-398: Improve print UI user feedback
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/modules/menu/components/print/MenuPrintSection.vue
Labels: feature

#785 PB-406: Updated canton Bern WMS urls
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
Labels: feature

#784 PB-393: Added copy button for embed iframe example
  src/modules/menu/components/share/MenuShareEmbed.vue
Labels: bug

#786 PB-396: Updated search bar e2e tests
  src/modules/menu/components/search/SearchBar.vue
  src/router/storeSync/abstractParamConfig.class.js
  src/router/storeSync/storeSync.routerPlugin.js
  src/store/modules/layers.store.js
  src/utils/utils.js
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: bug

#789 PB-360: Fix GPX layer printing issue
  src/modules/drawing/lib/style.js
  src/utils/gpxUtils.js
  src/utils/styleUtils.js
  tests/cypress/fixtures/print/line-and-marker.gpx
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#759 BGDIDIC-2749: poc with a master tileset for the vegetation
  src/modules/map/components/cesium/CesiumMap.vue
  src/store/modules/cesium.store.js
  tests/cypress/tests-e2e/3d/layers.cy.js
Labels: data-integration

#772 PB-397: Revert back print backend to correct staging on DEV
  src/api/print.api.js
Labels: feature

#782 PB-424: Time slider year entry button
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/toolbox/TimeSlider.vue
  tests/cypress/tests-e2e/timeSlider.cy.js
Labels: feature

#790 PB-426: Fallback to service search for invalid what3words
  src/store/modules/search.store.js
Labels: bug

#793 PB-389: Fix print attributions and duplicate legends
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  tests/cypress/tests-e2e/print.cy.js
Labels: feature

#728 PB-271: Add media buttons drawing mode
  src/config.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/DrawingStyleMediaTypes.enum.js
  src/modules/infobox/components/FeatureDetail.vue
  src/modules/infobox/components/FeatureDetailDisclaimer.vue
  src/modules/infobox/components/styling/DrawingStyleMediaLink.vue
  src/modules/infobox/components/styling/DrawingStylePopoverButton.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/modules/map/components/footer/MapFooterAttributionList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/scss/variables.scss
  src/scss/webmapviewer-bootstrap-theme.scss
  src/setup-fontawesome.js
  src/store/modules/ui.store.js
  src/utils/components/TextInput.vue
  src/utils/components/ThirdPartyDisclaimer.vue
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#794 PB-422: Fix social network sharing and added linkedin
  package-lock.json
  package.json
  src/main.js
  src/modules/i18n/locales/de.json
  src/modules/menu/components/share/MenuShareSocialNetworks.vue
  src/setup-fontawesome.js
  tests/cypress/tests-e2e/shareShortLink.cy.js
Labels: bug

#798 PB-440: Allow prefixed KML
  src/modules/menu/components/advancedTools/ImportFile/__tests__/utils.spec.js
  src/modules/menu/components/advancedTools/ImportFile/utils.js
Labels: bug

#800 PB-408: Add wms endpoint of BL to external provider list
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
Labels: feature

#799 PB-415: clear selected features when drawing mode is selected
  src/modules/drawing/components/DrawingToolboxButton.vue
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#801 PB-432: Allow text selection in layer info popup
  src/modules/menu/components/LayerDescriptionPopup.vue
Labels: bug

#797 PB-360: Update gpx line style and adjust line stroke width for printing.
  src/api/print.api.js
  src/modules/map/components/openlayers/utils/usePrint.composable.js
  src/store/modules/print.store.js
  src/utils/styleUtils.js
  tests/cypress/fixtures/print/capabilities.json
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#796 PB-438: Fix transparency of external WMS layers in print
  package-lock.json
  package.json
Labels: bug

#803 PB-304: Treasurehunt layer not displayed
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
Labels: bug

#804 PB-271: Fix compiler warning caused by unnecessary localization and i…
  src/modules/infobox/components/styling/DrawingStyleMediaLink.vue
Labels: bug

#807 PB-463: Fix KML share url
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/components/SharePopup.vue
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#805 PB-375: Added drawing to the report a problem
  src/api/feedback.api.js
  src/api/layers/KMLLayer.class.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingHeader.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/useKmlDataManagement.composable.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/InfoboxModule.vue
  src/modules/infobox/components/FeatureElevationProfile.vue
  src/modules/infobox/components/FeatureList.vue
  src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  src/modules/map/components/openlayers/OpenLayersVisibleLayers.vue
  src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  src/modules/map/components/toolbox/MapToolbox.vue
  src/modules/map/components/toolbox/Toggle3dButton.vue
  src/modules/menu/MenuModule.vue
  src/modules/menu/components/menu/MenuTray.vue
  src/modules/menu/components/settings/ReportProblemButton.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/store/modules/drawing.store.js
  src/store/modules/layers.store.js
  src/store/modules/ui.store.js
  src/store/plugins/click-on-map-management.plugin.js
  src/utils/components/DropdownButton.vue
  src/utils/components/ModalWithBackdrop.vue
  src/utils/kmlUtils.js
  src/views/MapView.vue
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/mouseposition.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
  tests/cypress/tests-e2e/toolboxRight.cy.js
Labels: feature
