Repository geoadmin/web-mapviewer, pull requests merged in 2024-11, with the labels that each got.

#1109 PB-875 : fix potential flakiness of tests
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: bug

#1108 PB-1116 : move drawing name to store
  src/api/layers/KMLLayer.class.js
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/useKmlDataManagement.composable.js
  src/store/modules/drawing.store.js
Labels: bug

#1111 PB-875 : new attempt at reducing this test flakiness on CI
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: bug

#1083 PB-1028 : do not load entire COGTIFF on import
  src/api/layers/CloudOptimizedGeoTIFFLayer.class.js
  src/api/layers/LayerTypes.enum.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
  src/modules/map/components/openlayers/OpenLayersInternalLayer.vue
  src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/index.js
  src/router/storeSync/LayerParamConfig.class.js
  src/store/index.js
  src/store/plugins/load-cog-extent.plugin.js
Labels: feature

#1107 PB-603: fix hover selected vertex and feature
  src/modules/drawing/components/DrawingTooltip.vue
  src/modules/drawing/lib/drawingUtils.js
Labels: bug

#1120 PB-789: fix compare slider description cut off
  src/modules/map/components/CompareSlider.vue
Labels: bug

#1118 PB-623: sync features when layers are updated
  src/modules/infobox/components/FeatureList.vue
  src/store/index.js
  src/store/modules/features.store.js
  src/store/plugins/update-selected-features.plugin.js
  tests/cypress/tests-e2e/featureSelection.cy.js
Labels: feature

#1098 PB-877: add swisssearch legacy url limit attribute
  src/api/search.api.js
  src/router/storeSync/SearchAutoSelectConfig.class.js
  src/router/storeSync/SearchParamConfig.class.js
  src/router/storeSync/storeSync.config.js
  src/store/modules/search.store.js
  src/store/plugins/redo-search-when-needed.plugin.js
  src/utils/searchParamUtils.js
  tests/cypress/tests-e2e/legacyParamImport.cy.js
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: feature

#1123 PB-1131: add warning when loading http resource
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/advancedTools/ImportFile/ImportFileOnlineTab.vue
Labels: bug

#1126 PB-1028 : fix COG loading after rebase error
  src/api/file-proxy.api.js
  src/api/files.api.js
  src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/FileParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/GPXParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/KMLParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/KMZParser.class.js
  src/modules/menu/components/advancedTools/ImportFile/parser/index.js
  src/store/plugins/load-cog-extent.plugin.js
  src/store/plugins/load-gpx-data.plugin.js
  src/store/plugins/load-kml-kmz-data.plugin.js
  tests/cypress/tests-e2e/print.cy.js
Labels: bug

#1127 PB-995: group all 3D background and visible layer into one component each
  src/modules/map/components/cesium/CesiumBackgroundLayer.vue
  src/modules/map/components/cesium/CesiumMap.vue
  src/modules/map/components/cesium/CesiumVectorLayer.vue
  src/modules/map/components/cesium/CesiumVisibleLayers.vue
  src/modules/map/components/cesium/utils/enhanceLabelStyle.js
  src/modules/map/components/cesium/utils/primitiveLayerUtils.js
  src/modules/map/components/cesium/utils/useAddPrimitiveLayer.composable.js
Labels: feature

#1117 PB-995: revert Cesium to 1.119 and fix Cesium CSS import warning
  package-lock.json
  package.json
  src/scss/main.scss
Labels: feature

#1125 PB-849: create profile multi segement gpx
  src/api/profile/ElevationProfile.class.js
  src/api/profile/profile.api.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
  src/modules/infobox/components/FeatureListCategoryItem.vue
  src/store/modules/features.store.js
  tests/cypress/fixtures/import-tool/external-gpx-file-multi-segment.gpx
  tests/cypress/tests-e2e/importToolFile.cy.js
Labels: feature

#1122 PB-1121: compare slider support for COGtiffs
  src/modules/map/components/CompareSlider.vue
  src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
  src/store/modules/ui.store.js
Labels: bug

#1124 PB-1140: add a minimal scale for print specs
  src/api/__tests__/print.api.spec.js
  src/api/print.api.js
  src/config/print.config.js
  src/utils/styleUtils.js
Labels: bug

#1047 PB-856 : add a style selector for KML in layer settings
  src/api/layers/KMLLayer.class.js
  src/api/layers/KmlStyles.enum.js
  src/modules/drawing/components/DrawingSelectInteraction.vue
  src/modules/drawing/components/useDrawingModeInteraction.composable.js
  src/modules/drawing/lib/export-utils.js
  src/modules/drawing/lib/style.js
  src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/router/storeSync/LayerParamConfig.class.js
  src/router/storeSync/layersParamParser.js
  src/store/plugins/load-kml-kmz-data.plugin.js
  src/utils/components/DropdownButton.vue
  src/utils/featureStyleUtils.js
  src/utils/kmlUtils.js
  src/utils/layerUtils.js
  src/utils/styleUtils.js
  tests/cypress/tests-e2e/print.cy.js
Labels: feature

#1106 PB-1080: show both warning and error feedback
  src/App.vue
  src/utils/components/ErrorWindow.vue
  src/utils/components/FeedbackPopup.vue
  src/utils/components/WarningWindow.vue
Labels: bug

#1133 fix translations
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: bug

#1134 New Release v1.48.1 - #patch
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
Labels: new-release

#1139 PB-1221 : partially out of bound KML was ignored entirely
  src/utils/__tests__/extentUtils.spec.js
  src/utils/extentUtils.js
  tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1140 PB-1211 : do not add ; if layer with feature selection is alone
  src/utils/legacyLayerParamUtils.js
Labels: bug

#1141 PB-1222 : fix mishandling of feature ID that are "number-like"
  src/router/storeSync/TimeSliderParamConfig.class.js
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/router/storeSync/layersParamParser.js
Labels: bug

#1137 PB-1128: fix permalink custom attributes
  src/store/modules/layers.store.js
  tests/cypress/tests-e2e/layers.cy.js
Labels: bug

#1142 New Release v1.48.2 - #patch
  src/router/storeSync/TimeSliderParamConfig.class.js
  src/router/storeSync/__tests__/layersParamParser.spec.js
  src/router/storeSync/layersParamParser.js
  src/store/modules/layers.store.js
  src/utils/__tests__/extentUtils.spec.js
  src/utils/extentUtils.js
  src/utils/legacyLayerParamUtils.js
  tests/cypress/tests-e2e/importToolFile.cy.js
  tests/cypress/tests-e2e/layers.cy.js
Labels: new-release

#1143 PB-1235 : make legend window adapt to its content
  src/modules/menu/components/LayerDescriptionPopup.vue
  src/utils/components/SimpleWindow.vue
Labels: bug

#1144 New Release v1.49.1 - #patch
  src/modules/menu/components/LayerDescriptionPopup.vue
  src/utils/components/SimpleWindow.vue
Labels: new-release

#1130 PB-1042: replace more information with news
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/help/MoreInfo.vue
  tests/cypress/tests-e2e/header.cy.js
Labels: feature

#1145 PB-1189: add layer feature search test
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: feature

#1146 PB-995 : Cesium WMTS as composable
  src/api/layers/ExternalWMTSLayer.class.js
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumVisibleLayers.vue
  src/modules/map/components/cesium/CesiumWMTSLayer.vue
  src/modules/map/components/cesium/utils/useAddImageryLayer.composable.js
  src/store/plugins/sync-camera-lonlatzoom.js
  tests/cypress/fixtures/layers.fixture.json
  tests/cypress/tests-e2e/3d/layers.cy.js
Labels: feature
