Repository geoadmin/web-mapviewer, pull requests merged in 2025-03, with the labels that each got.

#1240 PB-1200: Add Geolocation Test in 3D Map
  packages/mapviewer/src/modules/map/components/cesium/CesiumCamera.vue
  packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
  packages/mapviewer/src/store/plugins/geolocation-management.plugin.js
  packages/mapviewer/src/store/plugins/sync-camera-lonlatzoom.js
  packages/mapviewer/tests/cypress/support/commands.js
  packages/mapviewer/tests/cypress/tests-e2e/3d/geolocation.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/geolocation.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/legacyParamImport.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/utils.js
Labels: feature

#1234 Install vite-plugin-vue-devtools
  packages/mapviewer/cypress.config.mjs
  packages/mapviewer/package.json
  packages/mapviewer/vite.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature

#1226 PB 1052: Add 3d tooltips for buildings
  packages/mapviewer/src/api/layers/GeoAdmin3DLayer.class.js
  packages/mapviewer/src/config/cesium.config.js
  packages/mapviewer/src/modules/i18n/index.js
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
  packages/mapviewer/src/modules/infobox/components/FeatureList.vue
  packages/mapviewer/src/modules/infobox/components/FeatureListCategory.vue
  packages/mapviewer/src/modules/map/components/cesium/CesiumHighlightedFeatures.vue
  packages/mapviewer/src/modules/map/components/cesium/CesiumInteractions.vue
  packages/mapviewer/src/modules/map/components/cesium/CesiumPopover.vue
  packages/mapviewer/src/modules/map/components/cesium/locales/de.json
  packages/mapviewer/src/modules/map/components/cesium/locales/en.json
  packages/mapviewer/src/modules/map/components/cesium/locales/fr.json
  packages/mapviewer/src/modules/map/components/cesium/locales/it.json
  packages/mapviewer/src/modules/map/components/cesium/locales/rm.json
  packages/mapviewer/src/modules/map/components/cesium/utils/highlightUtils.js
  packages/mapviewer/src/store/modules/cesium.store.js
Labels: feature

#1260 PB-1435 Fix the german link to the feedback help page anchor
  packages/mapviewer/src/modules/i18n/README.md
  packages/mapviewer/src/modules/i18n/locales/de.json
Labels: bug

#1261 Fix the styling of the News Dropdown
  packages/mapviewer/src/modules/menu/components/header/AdditionalInfoCollapsable.vue
Labels: bug

#1263 PB-1261: add test case for void background
  packages/mapviewer/src/router/storeSync/storeSync.config.js
  packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
Labels: feature

#1264 PB-1137 : adding print view
  packages/geoadmin-coordinates/src/proj/CoordinateSystem.ts
  packages/geoadmin-coordinates/src/proj/StandardCoordinateSystem.ts
  packages/geoadmin-coordinates/src/proj/SwissCoordinateSystem.ts
  packages/geoadmin-coordinates/src/proj/WGS84CoordinateSystem.ts
  packages/geoadmin-coordinates/src/proj/WebMercatorCoordinateSystem.ts
  packages/mapviewer/src/App.vue
  packages/mapviewer/src/api/iframePostMessageEvent.api.js
  packages/mapviewer/src/api/shortlink.api.js
  packages/mapviewer/src/config/print.config.js
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/i18n/locales/en.json
  packages/mapviewer/src/modules/i18n/locales/fr.json
  packages/mapviewer/src/modules/i18n/locales/it.json
  packages/mapviewer/src/modules/i18n/locales/rm.json
  packages/mapviewer/src/modules/map/assets/north_arrow.png
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersPrintResolutionEnforcer.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersScale.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMSLayer.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersWMTSLayer.vue
  packages/mapviewer/src/modules/map/components/openlayers/debug/OpenLayersTileDebugInfo.vue
  packages/mapviewer/src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  packages/mapviewer/src/modules/menu/MenuModule.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugPrint.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugToolbar.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugViewSelector.vue
  packages/mapviewer/src/modules/menu/components/header/ConfederationFullLogo.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/src/router/__tests__/legacyPermalinkManagement.routerPlugin.spec.js
  packages/mapviewer/src/router/index.js
  packages/mapviewer/src/router/storeSync/PrintConfig.class.js
  packages/mapviewer/src/router/storeSync/storeSync.config.js
  packages/mapviewer/src/router/viewNames.js
  packages/mapviewer/src/scss/main.scss
  packages/mapviewer/src/store/modules/features.store.js
  packages/mapviewer/src/store/modules/map.store.js
  packages/mapviewer/src/store/modules/print.store.js
  packages/mapviewer/src/store/plugins/app-readiness.plugin.js
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/src/utils/layerUtils.js
  packages/mapviewer/src/views/EmbedView.vue
  packages/mapviewer/src/views/MapView.vue
  packages/mapviewer/src/views/PrintView.vue
  packages/mapviewer/tests/cypress/tests-e2e/embed.cy.js
Labels: feature

#1266 Include packages.json formatting in Prettier
  .prettierignore
  .prettierrc
  CONTRIBUTING.md
  adr/2021_04_14_drawing_library.md
  package.json
  packages/geoadmin-coordinates/src/proj/CoordinateSystem.ts
  packages/mapviewer/src/config/print.config.js
  packages/mapviewer/src/modules/map/components/cesium/locales/de.json
  packages/mapviewer/src/modules/map/components/cesium/locales/en.json
  packages/mapviewer/src/modules/map/components/cesium/locales/fr.json
  packages/mapviewer/src/modules/map/components/cesium/locales/it.json
  packages/mapviewer/src/modules/map/components/cesium/locales/rm.json
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersScale.vue
  packages/mapviewer/src/modules/map/components/openlayers/debug/OpenLayersTileDebugInfo.vue
  packages/mapviewer/src/modules/menu/MenuModule.vue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugPrint.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugViewSelector.vue
  packages/mapviewer/src/modules/menu/components/header/ConfederationFullLogo.vue
  packages/mapviewer/src/utils/debounce.ts
  packages/mapviewer/src/views/PrintView.vue
  packages/mapviewer/tests/cypress/tests-e2e/3d/geolocation.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/legacyParamImport.cy.js
  packages/mapviewer/vite.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature

#1249 PB-1004 : only use right click to trigger "delete point" action
  packages/mapviewer/src/modules/drawing/DrawingModule.vue
  packages/mapviewer/src/modules/drawing/components/useModifyInteraction.composable.js
  packages/mapviewer/tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#1255 PB-1456: Fix drag layer issue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Labels: bug

#1267 New Release v1.53.1 - #patch
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Labels: new-release

#1268 PB-1456: Fix dropping layer on itself deleting the dragged layer in active layer list.
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Labels: bug

#1272 New Release v1.53.2 - #patch
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
Labels: new-release

#1275 New Release v1.53.3 - #patch
  packages/mapviewer/src/modules/menu/components/header/ConfederationFullLogo.vue
Labels: new-release

#1271 PB-1539: Allow SMS URI in the external KML
  packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
  packages/mapviewer/tests/cypress/fixtures/import-tool/iframe-test.kml
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1278 PB-1548 : fix mismanagement of drawing features if coming with adminId
  packages/mapviewer/src/modules/drawing/DrawingModule.vue
Labels: bug

#1279 New Release v1.53.4 - #patch
  packages/mapviewer/src/modules/drawing/DrawingModule.vue
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/i18n/locales/en.json
  packages/mapviewer/src/modules/i18n/locales/fr.json
  packages/mapviewer/src/modules/i18n/locales/it.json
  packages/mapviewer/src/modules/i18n/locales/rm.json
  packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
  packages/mapviewer/src/store/plugins/load-kml-kmz-data.plugin.js
  packages/mapviewer/tests/cypress/fixtures/import-tool/iframe-test.kml
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: new-release

#1257 PB-1480: Fix bug with swissearch and crosshair together
  packages/mapviewer/src/router/storeSync/SearchParamConfig.class.js
  packages/mapviewer/src/store/modules/search.store.js
  packages/mapviewer/src/store/plugins/redo-search-when-needed.plugin.js
  packages/mapviewer/tests/cypress/support/commands.js
  packages/mapviewer/tests/cypress/tests-e2e/search/search-results.cy.js
Labels: bug

#1269 PB-1151: showing warning messages in the menu
  packages/mapviewer/src/api/layers/AbstractLayer.class.js
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/i18n/locales/en.json
  packages/mapviewer/src/modules/i18n/locales/fr.json
  packages/mapviewer/src/modules/i18n/locales/it.json
  packages/mapviewer/src/modules/i18n/locales/rm.json
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/useImportFile.composable.js
  packages/mapviewer/src/setup-fontawesome.js
  packages/mapviewer/src/utils/components/ExtLayerInfoButton.vue
Labels: feature

#1281 Fix flaky importToolMaps tests
  packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
Labels: bug

#1282 PB-1384 : tooltip module
  packages/geoadmin-tooltip/env.d.ts
  packages/geoadmin-tooltip/index.html
  packages/geoadmin-tooltip/package.json
  packages/geoadmin-tooltip/src/DevApp.vue
  packages/geoadmin-tooltip/src/GeoadminTooltip.vue
  packages/geoadmin-tooltip/src/dev.ts
  packages/geoadmin-tooltip/src/index.ts
  packages/geoadmin-tooltip/src/style.css
  packages/geoadmin-tooltip/tailwind.config.js
  packages/geoadmin-tooltip/tsconfig.json
  packages/geoadmin-tooltip/vite.config.js
  packages/mapviewer/package.json
  packages/mapviewer/src/App.vue
  packages/mapviewer/src/css/tailwind.css
  packages/mapviewer/src/modules/drawing/components/AddVertexButton.vue
  packages/mapviewer/src/modules/drawing/components/DrawingToolbox.vue
  packages/mapviewer/src/modules/infobox/components/FeatureAreaInfo.vue
  packages/mapviewer/src/modules/infobox/components/FeatureElevationProfileInformation.vue
  packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleIcon.vue
  packages/mapviewer/src/modules/infobox/components/styling/DrawingStylePopoverButton.vue
  packages/mapviewer/src/modules/map/components/LocationPopup.vue
  packages/mapviewer/src/modules/map/components/footer/backgroundSelector/bg-selector.scss
  packages/mapviewer/src/modules/map/components/openlayers/debug/OpenLayersDeviceOrientationDebugInfo.vue
  packages/mapviewer/src/modules/map/components/toolbox/FullScreenButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/TimeSlider.vue
  packages/mapviewer/src/modules/map/components/toolbox/TimeSliderButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/TimeSliderDropdown.vue
  packages/mapviewer/src/modules/map/components/toolbox/Toggle3dButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/ZoomButtons.vue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsListItem.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareInputCopyButton.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareSocialNetworks.vue
  packages/mapviewer/src/scss/main.scss
  packages/mapviewer/src/utils/components/CoordinateCopySlot.vue
  packages/mapviewer/src/utils/components/DropdownButton.vue
  packages/mapviewer/src/utils/components/ExtLayerInfoButton.vue
  packages/mapviewer/src/utils/components/PrintButton.vue
  packages/mapviewer/src/utils/components/TextTruncate.vue
  packages/mapviewer/src/utils/components/ThirdPartyDisclaimer.vue
  packages/mapviewer/src/utils/components/ZoomToExtentButton.vue
  packages/mapviewer/tailwind.config.js
  packages/mapviewer/tests/cypress/tests-component/TextTruncate.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
  packages/mapviewer/vite.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feature
