Repository geoadmin/web-mapviewer, pull requests merged in 2025-07, with the labels that each got.

#1365 PB-1699: White listing internal services used as an external provider
  packages/mapviewer/src/config/regex.config.ts
  packages/mapviewer/src/store/modules/layers.store.js
  packages/mapviewer/src/utils/kmlUtils.js
  packages/mapviewer/tests/cypress/fixtures/external-wms-getcap-1.fixture.xml
  packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
Labels: feature

#1372 New Release v1.57.1 - #patch
  packages/mapviewer/package.json
  packages/mapviewer/src/modules/drawing/components/DrawingExporter.vue
  packages/mapviewer/src/modules/map/components/openlayers/utils/usePrint.composable.js
  packages/mapviewer/src/modules/menu/components/print/MenuPrintSection.vue
  packages/mapviewer/src/utils/utils.js
  packages/mapviewer/tests/cypress/tests-e2e/print.cy.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: new-release

#1375 PB-1816: narrowing index.html cache definition to current origin only
  packages/mapviewer/src/config/baseUrl.config.js
  packages/mapviewer/src/service-workers.ts
Labels: bug

#1377 PB-1784: Use eye for KML description visibility and add tooltip for other buttons
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/i18n/locales/en.json
  packages/mapviewer/src/modules/i18n/locales/fr.json
  packages/mapviewer/src/modules/i18n/locales/it.json
  packages/mapviewer/src/modules/i18n/locales/rm.json
  packages/mapviewer/src/modules/infobox/components/styling/FeatureStyleEdit.vue
  packages/mapviewer/src/setup-fontawesome.js
Labels: feature

#1376 PB-1827: change service-worker strategy to network first
  packages/mapviewer/src/config/baseUrl.config.js
  packages/mapviewer/src/service-workers.ts
  packages/mapviewer/src/utils/offline/OfflineReadinessStatus.vue
  packages/mapviewer/vite.config.mts
Labels: bug

#1379 PB-1828: Fix description always shown.
  packages/mapviewer/src/store/modules/features.store.js
  packages/mapviewer/src/utils/kmlUtils.js
Labels: bug

#1378 PB-1834: Layer "Notifications for maps an geodata" not loading
  packages/mapviewer/src/modules/map/components/openlayers/utils/styleFromLiterals.js
Labels: bug

#1384 New Release v1.58.0 - #minor
  packages/mapviewer/src/service-workers.ts
Labels: new-release
