Repository geoadmin/web-mapviewer, pull requests merged in 2025-05, with the labels that each got.

#1318 PB-1320: Support More Thousand Separator on Search
  packages/mapviewer/src/utils/coordinates/__test__/coordinateExtractors.spec.js
  packages/mapviewer/src/utils/coordinates/coordinateExtractors.js
Labels: feature

#1325 PB-1427: Support uppercase language parameter
  packages/mapviewer/src/modules/menu/components/help/MenuHelpSection.vue
  packages/mapviewer/src/router/storeSync/storeSync.config.js
  packages/mapviewer/src/store/modules/i18n.store.js
  packages/mapviewer/tests/cypress/tests-e2e/changeLanguage.cy.js
Labels: bug

#1324 PB-1665: offer option to remove debug mode from dev site
  packages/mapviewer/src/modules/menu/components/debug/DebugToolbar.vue
  packages/mapviewer/src/setup-fontawesome.js
  packages/mapviewer/src/store/modules/ui.store.js
Labels: feature

#1310 PB-1603: add stylelint
  package.json
  packages/mapviewer/src/modules/infobox/components/FeatureAreaInfo.vue
  packages/mapviewer/src/modules/infobox/components/FeatureList.vue
  packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleColorSelector.vue
  packages/mapviewer/src/modules/map/components/MapPopover.vue
  packages/mapviewer/src/modules/map/components/footer/backgroundSelector/BackgroundSelectorSquared.vue
  packages/mapviewer/src/modules/map/components/footer/backgroundSelector/bg-selector.scss
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersMap.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersScale.vue
  packages/mapviewer/src/modules/map/components/toolbox/FullScreenButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/TimeSlider.vue
  packages/mapviewer/src/modules/map/scss/toolbox-buttons.scss
  packages/mapviewer/src/modules/menu/MenuModule.vue
  packages/mapviewer/src/modules/menu/components/3d/MenuThreeD.vue
  packages/mapviewer/src/modules/menu/components/LayerCatalogueItem.vue
  packages/mapviewer/src/modules/menu/components/LayerDescriptionPopup.vue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  packages/mapviewer/src/modules/menu/components/activeLayers/MenuActiveLayersListItemTimeSelector.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportCatalogue/ProviderList.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportCatalogue/ProviderUrl.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsListItem.vue
  packages/mapviewer/src/modules/menu/components/common/MenuItemCheckBox.vue
  packages/mapviewer/src/modules/menu/components/debug/DebugToolbar.vue
  packages/mapviewer/src/modules/menu/components/header/ConfederationFullLogo.vue
  packages/mapviewer/src/modules/menu/components/search/SearchBar.vue
  packages/mapviewer/src/modules/menu/components/search/SearchResultListEntry.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareInputCopyButton.vue
  packages/mapviewer/src/modules/menu/components/topics/MenuTopicSelectionPopup.vue
  packages/mapviewer/src/modules/menu/scss/menu-items.scss
  packages/mapviewer/src/modules/menu/scss/topics-image.scss
  packages/mapviewer/src/scss/main.scss
  packages/mapviewer/src/scss/media-query.mixin.scss
  packages/mapviewer/src/scss/variables-admin.module.scss
  packages/mapviewer/src/scss/variables.module.scss
  packages/mapviewer/src/scss/webmapviewer-bootstrap-theme.scss
  packages/mapviewer/src/utils/components/CoordinateCopySlot.vue
  packages/mapviewer/src/utils/components/ExtLayerInfoButton.vue
  packages/mapviewer/src/utils/components/ModalWithBackdrop.vue
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/src/utils/components/ThirdPartyDisclaimer.vue
  packages/mapviewer/src/utils/styleUtils.js
  packages/mapviewer/src/views/LegacyParamsView.vue
  packages/mapviewer/vite.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  stylelint.config.js
Labels: feature

#1313 PB-1179: highlight current segment multi line profile
  packages/mapviewer/src/modules/infobox/components/InfoboxContent.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersHighlightedFeatures.vue
  packages/mapviewer/src/modules/map/components/openlayers/utils/markerStyle.js
  packages/mapviewer/src/store/modules/profile.store.js
  packages/mapviewer/tests/cypress/fixtures/import-tool/external-gpx-file-multi-separated-segment.gpx
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: feature

#1329 PB-1179: Zoom-to-extent zooms on current profile segment
  packages/mapviewer/src/modules/infobox/InfoboxModule.vue
  packages/mapviewer/src/modules/infobox/components/InfoboxContent.vue
  packages/mapviewer/src/store/modules/profile.store.js
Labels: feature

#1328 PB-1671: removing invalid URLs from external providers whitelist
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
Labels: bug

#1331 PB-1672: fix menu collapse
  packages/mapviewer/.env.test
  packages/mapviewer/cypress.config.mjs
  packages/mapviewer/package.json
  packages/mapviewer/src/modules/menu/components/LayerCatalogueItem.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  packages/mapviewer/src/modules/menu/components/help/MenuHelpSection.vue
  packages/mapviewer/src/modules/menu/components/menu/MenuSection.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/menuTray.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/topics.cy.js
  packages/mapviewer/vite.config.mts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#1333 PB-1670: clarify lack of precision of mouse tracked LV03 coordinates
  packages/mapviewer/src/modules/map/components/cesium/CesiumMouseTracker.vue
  packages/mapviewer/src/modules/map/components/common/mouseTrackerUtils.js
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersMouseTracker.vue
Labels: feature

#1332 PB-1674: Fix tooltip creating too much height with map buttons
  packages/geoadmin-tooltip/src/GeoadminTooltip.vue
  packages/mapviewer/src/modules/map/components/toolbox/GeolocButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/Toggle3dButton.vue
  packages/mapviewer/src/modules/map/components/toolbox/ZoomButtons.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareInputCopyButton.vue
  packages/mapviewer/src/utils/components/ExtLayerInfoButton.vue
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/layers.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/mouseposition.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/shareShortLink.cy.js
Labels: bug

#1336 PB-1179: fix profile segment test not passing on CI
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1334 PB-1579: add support for local BigTIFF
  package.json
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/CloudOptimizedGeoTIFFParser.class.js
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/FileParser.class.js
  packages/mapviewer/src/modules/menu/components/advancedTools/ImportFile/parser/KMZParser.class.js
Labels: feature

#1338 New Release v1.55.1 - #patch
  packages/mapviewer/src/modules/menu/components/menu/MenuSection.vue
Labels: new-release

#1340 PB-1698: fix scroll issue with new collapse component
  packages/mapviewer/package.json
  packages/mapviewer/src/modules/menu/components/LayerCatalogueItem.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  packages/mapviewer/src/modules/menu/components/menu/MenuSection.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/topics.cy.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#1341 PB-1697: limiting floating window's height
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/tests/cypress/tests-e2e/reportProblem.cy.js
Labels: bug

#1343 Attempt at reducing CI flakiness
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1342 New Release v1.55.2 - #patch
  packages/mapviewer/package.json
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
  packages/mapviewer/src/modules/menu/components/LayerCatalogueItem.vue
  packages/mapviewer/src/modules/menu/components/advancedTools/MenuAdvancedToolsList.vue
  packages/mapviewer/src/modules/menu/components/menu/MenuSection.vue
  packages/mapviewer/src/modules/menu/components/share/MenuShareEmbed.vue
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/importToolMaps.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/reportProblem.cy.js
  packages/mapviewer/tests/cypress/tests-e2e/topics.cy.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: new-release

#1346 PB-1685: duplicate COG layers from WMS can't be compared
  packages/mapviewer/src/modules/map/components/CompareSlider.vue
Labels: bug

#1345 PB-1054 : Remove mouse events from useMovableElement and replace with pointer events
  packages/mapviewer/src/modules/map/components/MapPopover.vue
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/src/utils/composables/useMovableElement.composable.js
Labels: bug

#1347 New Release v1.55.3 - #patch
  packages/mapviewer/src/modules/map/components/CompareSlider.vue
  packages/mapviewer/src/modules/map/components/MapPopover.vue
  packages/mapviewer/src/utils/components/SimpleWindow.vue
  packages/mapviewer/src/utils/composables/useMovableElement.composable.js
Labels: new-release

#1304 PB-1491 : Add a test to parse an online kml with the wrong content-type
  packages/mapviewer/tests/cypress/tests-e2e/importToolFile.cy.js
Labels: bug

#1322 PB-1300: KML feature selection 3D
  packages/mapviewer/src/modules/infobox/components/FeatureDetail.vue
  packages/mapviewer/src/modules/map/components/cesium/CesiumInteractions.vue
  packages/mapviewer/src/modules/map/components/cesium/CesiumKMLLayer.vue
  packages/mapviewer/src/modules/map/components/openlayers/utils/useMapInteractions.composable.js
  packages/mapviewer/src/store/plugins/reproject-layers-on-projection-change.plugin.js
  packages/mapviewer/src/utils/kmlUtils.js
  packages/mapviewer/src/utils/layerUtils.js
  packages/mapviewer/tests/cypress/tests-e2e/3d/featureSelection.cy.js
Labels: feature

#1351 PB-1257: add tile debug for COGs
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
Labels: bug

#1349 PB-1679: fix local cog file compare
  packages/mapviewer/src/modules/map/components/CompareSlider.vue
  packages/mapviewer/src/modules/map/components/openlayers/OpenLayersCOGTiffLayer.vue
Labels: bug

#1350 PB-1680 : Fix icon selector border
  packages/mapviewer/src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
Labels: bug

#1339 PB-1695: add the option to show marker description on the map
  packages/mapviewer/src/api/features/EditableFeature.class.js
  packages/mapviewer/src/modules/drawing/components/DrawingSelectInteraction.vue
  packages/mapviewer/src/modules/drawing/components/useDrawingModeInteraction.composable.js
  packages/mapviewer/src/modules/i18n/locales/de.json
  packages/mapviewer/src/modules/i18n/locales/en.json
  packages/mapviewer/src/modules/i18n/locales/fr.json
  packages/mapviewer/src/modules/i18n/locales/it.json
  packages/mapviewer/src/modules/i18n/locales/rm.json
  packages/mapviewer/src/modules/infobox/components/InfoboxContent.vue
  packages/mapviewer/src/modules/infobox/components/styling/FeatureStyleEdit.vue
  packages/mapviewer/src/store/modules/features.store.js
  packages/mapviewer/src/utils/featureStyleUtils.js
  packages/mapviewer/src/utils/kmlUtils.js
Labels: feature
