Repository geoadmin/web-mapviewer, pull requests merged in 2025-01, with the labels that each got.

#1179 PB-1310: 3D navigation compass was not showing
  src/modules/map/components/cesium/CesiumMap.vue
Labels: hotfix

#1161 PB-1263: add handleLegacyParam function tests
  src/router/__tests__/legacyPermalinkManagement.routerPlugin.spec.js
  src/router/legacyPermalinkManagement.routerPlugin.js
Labels: feature

#1178 PB-326: check external provider get map
  package-lock.json
  package.json
  scripts/check-external-layers-providers.js
  src/api/layers/layers-external.api.js
Labels: feature

#1184 PB-1195: Add test for printing WMS and WMTS layers.
  tests/cypress/tests-e2e/print.cy.js
Labels: feature

#1100 PB-1037: Add dropdown to select feedback category
  src/api/feedback.api.js
  src/config/feedback.config.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/debug/BaseUrlOverrideModal.vue
  src/modules/menu/components/help/ReportProblemButton.vue
  src/modules/menu/components/help/feedback/FeedbackButton.vue
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: feature

#1189 PB-1213: Fix unhandled null.
  src/modules/drawing/components/DrawingInteractions.vue
Labels: bug

#1187 PB-1187: Add more geolocation test
  src/modules/i18n/index.js
  src/store/plugins/geolocation-management.plugin.js
  src/utils/components/FeedbackPopup.vue
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/geolocation.cy.js
Labels: feature

#1183 PB-1151: refactor feature Elevation component
  src/modules/infobox/components/FeatureElevationProfilePlot.vue
Labels: feature

#1185 PB-1031: Add a github link to the version
  src/config/staging.config.js
  src/setup-fontawesome.js
  src/utils/components/AppVersion.vue
Labels: feature

#1173 PB-1296 : remove ol-cesium shallow copy
  src/api/layers/KMLLayer.class.js
  src/config/cesium.config.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/map/components/cesium/CesiumGPXLayer.vue
  src/modules/map/components/cesium/CesiumGeoJSONLayer.vue
  src/modules/map/components/cesium/CesiumInteractions.vue
  src/modules/map/components/cesium/CesiumInternalLayer.vue
  src/modules/map/components/cesium/CesiumKMLLayer.vue
  src/modules/map/components/cesium/CesiumVectorLayer.vue
  src/modules/map/components/cesium/utils/addPrimitiveFromOLLayer.mixins.js
  src/modules/map/components/cesium/utils/olcs/FeatureConverter.ts
  src/modules/map/components/cesium/utils/olcs/README.md
  src/modules/map/components/cesium/utils/olcs/VectorLayerCounterpart.ts
  src/modules/map/components/cesium/utils/olcs/core.ts
  src/modules/map/components/cesium/utils/olcs/util.ts
  src/modules/map/components/cesium/utils/primitiveLayerUtils.js
  src/modules/map/components/cesium/utils/styleConverter.js
  src/modules/map/components/cesium/utils/swissnamesStyle.js
  src/modules/map/components/cesium/utils/useAddDataSourceLayer.composable.js
  src/modules/map/components/cesium/utils/useAddPrimitiveLayer.composable.js
  src/modules/map/components/openlayers/utils/styleFromLiterals.js
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/router/storeSync/layersParamParser.js
  tests/cypress/fixtures/geojson-style.fixture.json
  tests/cypress/fixtures/geojson.fixture.json
  tests/cypress/tests-e2e/3d/layers.cy.js
Labels: feature

#1193 PB-1186: Add test for landscape mobile from the portrait one and adapt accordingly.
  tests/cypress/tests-e2e/menuTray.cy.js
Labels: feature

#1194 PB-400: Add test for hiding the dropdown adter selecting a search result
  tests/cypress/tests-e2e/search/search-results.cy.js
Labels: feature

#1182 PB-1297: make position of text labels configurable
  src/api/features/EditableFeature.class.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/DrawingStylePlacementSelector.vue
  src/modules/infobox/components/styling/FeatureStyleEdit.vue
  src/store/modules/features.store.js
  src/utils/featureStyleUtils.js
  src/utils/kmlUtils.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: feature

#1191 PB-1327: Refactored 'DropdownItem' to translate the button title internally
  src/modules/drawing/components/DrawingExporter.vue
  src/modules/i18n/index.js
  src/modules/infobox/components/styling/DrawingStyleIconSelector.vue
  src/modules/infobox/components/styling/DrawingStyleSizeSelector.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/help/ReportProblemButton.vue
  src/utils/components/DropdownButton.vue
  src/utils/components/SimpleWindow.vue
  tests/cypress/tests-e2e/feedbackTestUtils.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: bug

#1198 PB-1343: add "more info" link in problem report form
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  src/modules/menu/components/help/ReportProblemButton.vue
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: feature

#1203 Update build badges
  README.md
Labels: skip-relase-note

#1210 PB-1355 : don't show drawing lost warning when we open download PDFs
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/store/modules/ui.store.js
  src/views/MapView.vue
Labels: bug

#1211 PB 1358: fix issue with printing imported KMLS
  src/api/print.api.js
Labels: bug

#1212 New Release v1.51.1 - #patch
  src/api/print.api.js
  src/api/profile/profile.api.js
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/menu/components/help/ReportProblemButton.vue
  src/modules/menu/components/print/MenuPrintSection.vue
  src/store/modules/ui.store.js
  src/views/MapView.vue
  tests/cypress/fixtures/import-tool/big-external-kml-file.kml
  tests/cypress/tests-e2e/importToolFile.cy.js
  tests/cypress/tests-e2e/reportProblem.cy.js
Labels: new-release

#1214 PB 1358: Allow printing measures again
  src/api/print.api.js
Labels: bug

#1215 PB-1349: new layers geodienste.ch
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
Labels: feature

#1149 PB-1192: add test move and resize legend
  src/utils/components/SimpleWindow.vue
  tests/cypress/fixtures/legend.fixture.html
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/topics.cy.js
Labels: feature

#1218 New Release v1.51.2 - #patch
  src/api/print.api.js
  src/modules/menu/components/activeLayers/MenuActiveLayersList.vue
  src/modules/menu/components/activeLayers/MenuActiveLayersListItem.vue
  src/modules/menu/components/advancedTools/ImportCatalogue/external-providers.json
  src/store/modules/features.store.js
  src/store/modules/layers.store.js
  src/utils/components/SimpleWindow.vue
  tests/cypress/fixtures/html-popup-german.fixture.html
  tests/cypress/fixtures/legend.fixture.html
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/drawing.cy.js
  tests/cypress/tests-e2e/infobox.cy.js
  tests/cypress/tests-e2e/layers.cy.js
  tests/cypress/tests-e2e/topics.cy.js
Labels: new-release

#1220 PB-1299, PB-1344: Opening Drawing module with pre-loaded empty KML breaks the drawing module
  src/modules/drawing/DrawingModule.vue
  src/modules/drawing/components/DrawingToolbox.vue
  src/modules/drawing/useKmlDataManagement.composable.js
  src/views/MapView.vue
  tests/cypress/fixtures/post-kml.fixture.json
  tests/cypress/support/drawing.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#1216 PB-1031: redirect github link to release page
  src/utils/components/AppVersion.vue
Labels: feature

#1222 PB-1004: Drawing polygone - Move delete point to right click
  src/modules/drawing/components/useModifyInteraction.composable.js
  src/modules/i18n/locales/de.json
  src/modules/i18n/locales/en.json
  src/modules/i18n/locales/fr.json
  src/modules/i18n/locales/it.json
  src/modules/i18n/locales/rm.json
  tests/cypress/support/commands.js
  tests/cypress/tests-e2e/drawing.cy.js
Labels: bug

#1223 PB-1322: Compare slider external layer not correctly cut after reloading
  src/modules/map/components/CompareSlider.vue
Labels: bug
